-- Generated by worker/seed/generate-seed-sql.ts from worker/seed/units.json. Do not hand-edit.
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('71ab56d9-2f0b-4996-bc5b-634f568048bd', 'money-mindset-goals', 'Money Mindset & Goals', 0, NULL);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('297ff0b8-4538-45da-811f-3725e73c5efa', '71ab56d9-2f0b-4996-bc5b-634f568048bd', 'Why Financial Literacy Matters', '## Why This Matters

Money isn''t just numbers — it''s a tool for buying *time*, *options*, and *security*. People who understand a few core concepts (budgeting, saving, compound interest) consistently make better long-term decisions than those who don''t, regardless of how much they earn.

This course won''t tell you what stocks to buy or make you rich overnight. It teaches the fundamentals: how to control your spending, build a safety net, and understand how money grows over time.

**This is educational content, not financial advice.**', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('d5186bbf-dab5-439f-b7e3-dab213e509ae', '297ff0b8-4538-45da-811f-3725e73c5efa', 'What is the main goal of this course?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b57b37fc-7a7f-4898-a64d-e63196f715df', 'd5186bbf-dab5-439f-b7e3-dab213e509ae', 'To teach core financial concepts and habits', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('fae4ae87-46db-4b08-8c4b-068c966e5d73', 'd5186bbf-dab5-439f-b7e3-dab213e509ae', 'To give you specific stock picks', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('30a7719a-f21f-487c-9b30-151771029bb9', 'd5186bbf-dab5-439f-b7e3-dab213e509ae', 'To guarantee you get rich quickly', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('0729cbef-5f59-4909-ac12-ab634395f583', '297ff0b8-4538-45da-811f-3725e73c5efa', 'True or false: understanding money matters even if you don''t earn a lot.', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('35f86983-0cf5-440d-946f-a98f17fd1290', '0729cbef-5f59-4909-ac12-ab634395f583', 'True', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('d1eb71d9-d39b-42e5-957e-ad0abb7f52a8', '0729cbef-5f59-4909-ac12-ab634395f583', 'False', 0, 1);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('7f6c682b-915d-468b-971e-00745033f092', '71ab56d9-2f0b-4996-bc5b-634f568048bd', 'Setting a Financial Goal', '## Setting a Financial Goal

A goal without a number and a date is just a wish. Compare:

- ❌ "I want to save more money."
- ✅ "I want to save $1,000 for an emergency fund in the next 6 months."

Good financial goals are **specific** (a clear target), **measurable** (a number), and **time-bound** (a deadline). This makes it possible to track progress and know when you''ve actually succeeded.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('df2993b0-215d-4a59-8c53-c8aea5b37e66', '7f6c682b-915d-468b-971e-00745033f092', 'Which of these is the BEST example of a specific financial goal?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('c4818c06-36b3-4394-8824-8f6431d81996', 'df2993b0-215d-4a59-8c53-c8aea5b37e66', 'Save $1,000 for an emergency fund in 6 months', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('bfb737fa-f158-4db7-a526-267d300c9d63', 'df2993b0-215d-4a59-8c53-c8aea5b37e66', 'Try to save some money this year', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('004e734a-d045-4616-88a0-9d31da73e7a4', 'df2993b0-215d-4a59-8c53-c8aea5b37e66', 'Be better with money', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('8feddba8-9526-4c2a-8738-6902b406f607', '7f6c682b-915d-468b-971e-00745033f092', 'A good financial goal should be specific, measurable, and...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('42a8c9be-e4ea-4352-9bae-750b278a7497', '8feddba8-9526-4c2a-8738-6902b406f607', 'Time-bound', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a0544430-0ba8-4ea4-9768-238700bb22f1', '8feddba8-9526-4c2a-8738-6902b406f607', 'Secret', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('c84bb99d-1070-4df4-a665-96164767c265', '8feddba8-9526-4c2a-8738-6902b406f607', 'Unlimited', 0, 2);
