-- Generated by worker/seed/generate-seed-sql.ts from worker/seed/units.json. Do not hand-edit.
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('228e6eaf-081c-4533-b007-b5a925524c81', 'budgeting-basics', 'Budgeting Basics', 1, '71ab56d9-2f0b-4996-bc5b-634f568048bd');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('7975c632-9181-4cfd-be04-db837d2e92d1', '228e6eaf-081c-4533-b007-b5a925524c81', 'Income vs. Expenses', '## Income vs. Expenses

Every budget starts with one equation:

**Income − Expenses = Surplus (or Deficit)**

- **Income** is money coming in: salary, side gigs, gifts.
- **Expenses** are money going out: rent, food, subscriptions.

If you spend less than you earn, you have a **surplus** — money you can save or invest. If you spend more than you earn, you have a **deficit**, and the gap usually goes on a credit card, which makes next month harder.

A budget is simply a *plan* for this equation, made *before* the month starts instead of discovering the result after.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('d00365ec-f131-43a0-bf38-b631bf3ecb65', '7975c632-9181-4cfd-be04-db837d2e92d1', 'You earn $3,000 a month and spend $3,200. You have a...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('61839d6e-a821-4010-bb1c-1fde09204da9', 'd00365ec-f131-43a0-bf38-b631bf3ecb65', 'Deficit of $200', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('d5d7d02e-f036-4ec7-952c-dffde87e350b', 'd00365ec-f131-43a0-bf38-b631bf3ecb65', 'Surplus of $200', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('85bacbd8-67bd-4edd-9aca-8fd60f664576', 'd00365ec-f131-43a0-bf38-b631bf3ecb65', 'Balanced budget', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('99c97b80-70e1-485e-b595-c8f334357c0d', '7975c632-9181-4cfd-be04-db837d2e92d1', 'What is a budget, most simply?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('9537f015-b663-4320-ad99-4fdfc837d7f0', '99c97b80-70e1-485e-b595-c8f334357c0d', 'A plan for your income and expenses made in advance', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('367a3490-452d-4aa1-b40a-2f1927d668cb', '99c97b80-70e1-485e-b595-c8f334357c0d', 'A punishment for overspending', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('fd2b1f8a-60de-411b-a44d-f7a3daca513e', '99c97b80-70e1-485e-b595-c8f334357c0d', 'A bank account with restrictions', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('ae5fdcd6-315d-4b89-85a1-77d5997a9d32', '228e6eaf-081c-4533-b007-b5a925524c81', 'The 50/30/20 Rule', '## The 50/30/20 Rule

A simple starting budget for your *take-home pay* (what actually hits your bank account after taxes):

- **50% Needs** — rent, groceries, utilities, insurance, minimum debt payments
- **30% Wants** — dining out, streaming, hobbies, travel
- **20% Savings & extra debt payoff** — emergency fund, investing, extra payments

The exact split doesn''t matter; the *habit* does. If 50/30/20 doesn''t fit your city''s rent, try 60/20/20 — just keep savings above zero.

**Pro tip:** move savings out on payday, not at month''s end. What''s left over tends to vanish; what''s moved first tends to stick.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('0618d8c4-5aa2-44f8-92bf-15f0feaee800', 'ae5fdcd6-315d-4b89-85a1-77d5997a9d32', 'In the 50/30/20 rule, what does the 20% represent?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0c48472d-8b6b-461e-a2a9-3ab21f9d247a', '0618d8c4-5aa2-44f8-92bf-15f0feaee800', 'Savings and extra debt payoff', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ed169a82-6b45-41b3-9bc5-a966ffc633ef', '0618d8c4-5aa2-44f8-92bf-15f0feaee800', 'Rent and utilities', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b8d4c93c-e524-47dd-b62b-e2814831b49a', '0618d8c4-5aa2-44f8-92bf-15f0feaee800', 'Dining out and entertainment', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('eccd1160-f8e8-4fd0-8a68-c31b2595ba0e', 'ae5fdcd6-315d-4b89-85a1-77d5997a9d32', 'Why save money on payday instead of at the end of the month?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('95642fbe-5212-4e53-a20a-b0ae26e1733e', 'eccd1160-f8e8-4fd0-8a68-c31b2595ba0e', 'Money moved first tends to stay saved; leftovers tend to get spent', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3c1e398f-48bd-452a-b711-cd09e302254e', 'eccd1160-f8e8-4fd0-8a68-c31b2595ba0e', 'Banks only accept deposits on payday', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('757341f4-c5e6-489c-87e5-84396627234c', 'eccd1160-f8e8-4fd0-8a68-c31b2595ba0e', 'It earns double interest that way', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('e807ddd7-87ad-48fc-9bae-1a9499030d1f', 'tracking-spending', 'Tracking Spending', 2, '228e6eaf-081c-4533-b007-b5a925524c81');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('5481d79d-147e-4dee-ad72-c6246d884919', 'e807ddd7-87ad-48fc-9bae-1a9499030d1f', 'Needs vs. Wants', '## Needs vs. Wants

- **Needs** keep you housed, fed, and employable: rent, groceries, basic clothes, insurance, minimum debt payments.
- **Wants** make life enjoyable: restaurants, games, concerts, a nicer phone.

The test is *situational*, not moral. Food is a need; a $60 dinner is a want. A phone may be a need for your job; the latest flagship model is a want.

Wants aren''t bad — a budget with zero fun almost never survives. The goal is to **choose** your wants deliberately instead of discovering them on your credit card statement.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('fab7c7e6-6964-4c01-81dc-895af4b6c5c3', '5481d79d-147e-4dee-ad72-c6246d884919', 'Which of these is clearly a NEED?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ab80aa12-8895-406f-a04a-e34215785121', 'fab7c7e6-6964-4c01-81dc-895af4b6c5c3', 'Groceries for the week', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('52a846c1-0cfa-4de1-80f0-d8e0c20f21ae', 'fab7c7e6-6964-4c01-81dc-895af4b6c5c3', 'Concert tickets', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('dcfdfc20-76fc-4cf0-b055-35894c617625', 'fab7c7e6-6964-4c01-81dc-895af4b6c5c3', 'A premium streaming bundle', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('a3b28c2f-6211-45ff-bbe3-46014745280d', '5481d79d-147e-4dee-ad72-c6246d884919', 'The needs-vs-wants test is best described as...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('2ad97328-f66f-44d0-a56e-8938713299a7', 'a3b28c2f-6211-45ff-bbe3-46014745280d', 'Situational — it depends on your circumstances', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('cbd24968-a45b-4939-9a71-2230d055b326', 'a3b28c2f-6211-45ff-bbe3-46014745280d', 'Fixed — the same items for everyone, always', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f2fabb04-4cfc-4f48-8667-ba47fd5bf326', 'a3b28c2f-6211-45ff-bbe3-46014745280d', 'Moral — wants should be eliminated', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('13483e29-bb3f-433e-b466-ffdd44bf2e89', 'e807ddd7-87ad-48fc-9bae-1a9499030d1f', 'Spotting Leaks', '## Spotting Leaks

Small recurring charges drain serious money:

- A $12 subscription is **$144 a year**.
- Three forgotten subscriptions at $15 each are **$540 a year**.

**How to find your leaks:**

1. Pull last month''s bank and card statements.
2. Highlight every recurring charge.
3. For each one ask: *"Would I sign up for this again today at 12× the price?"*
4. Cancel the ones that fail the test — ruthlessly. You can always re-subscribe.

Most people find $50–$200/month of spending they don''t miss once it''s gone. That''s the cheapest raise you''ll ever get.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f75df661-3dfb-46c4-b6b7-e83ecc15b657', '13483e29-bb3f-433e-b466-ffdd44bf2e89', 'A $12/month subscription costs how much per year?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('466112d5-122d-4473-8e44-2dfeb498e29e', 'f75df661-3dfb-46c4-b6b7-e83ecc15b657', '$144', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0e8adafe-cc11-403f-b50a-cb6ec2987ec0', 'f75df661-3dfb-46c4-b6b7-e83ecc15b657', '$120', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('41d08fd5-0a21-48e0-b115-34f49c0d39e6', 'f75df661-3dfb-46c4-b6b7-e83ecc15b657', '$1,200', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('a742f54f-89b3-4b0e-b33d-f9946896f2a6', '13483e29-bb3f-433e-b466-ffdd44bf2e89', 'What''s the best question to ask about a recurring charge?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('9a768afa-e8d2-485c-8486-a9355b9662a1', 'a742f54f-89b3-4b0e-b33d-f9946896f2a6', '"Would I sign up for this again today at 12× the price?"', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a3258150-cbba-4ef3-8c4f-bc5ae72b9c5e', 'a742f54f-89b3-4b0e-b33d-f9946896f2a6', '"Did I use it at least once?"', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f61747df-b011-421b-8ba2-15f3fa65ffc2', 'a742f54f-89b3-4b0e-b33d-f9946896f2a6', '"Is it cheaper than my other subscriptions?"', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('b63b68ec-b31a-4174-85a4-d538ce92be4c', 'emergency-funds', 'Emergency Funds', 3, 'e807ddd7-87ad-48fc-9bae-1a9499030d1f');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('147080d8-8fb9-4e8f-b52f-b989ed560879', 'b63b68ec-b31a-4174-85a4-d538ce92be4c', 'Why You Need One', '## Why You Need One

Life throws surprises: a car repair, a medical bill, a layoff. Without savings, every surprise goes on a credit card — and debt at 20%+ interest turns one bad week into months of expensive payments. That''s the **debt spiral**.

An **emergency fund** is cash reserved *only* for genuine emergencies:

- ✅ Car breaks down, job loss, surprise medical bill
- ❌ A sale on flights, a new phone, concert tickets

It''s the difference between "annoying" and "disaster." A $1,000 surprise with no savings is a crisis; with savings it''s a Tuesday.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('addf5b8d-0a48-4954-894a-26b18aa4af72', '147080d8-8fb9-4e8f-b52f-b989ed560879', 'The main purpose of an emergency fund is to...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('2404dced-c00f-4562-952a-d2281a23f8a5', 'addf5b8d-0a48-4954-894a-26b18aa4af72', 'Cover genuine surprises without going into debt', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0fe906d9-031e-4fce-8550-6bc092fc1537', 'addf5b8d-0a48-4954-894a-26b18aa4af72', 'Fund vacations at short notice', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0357bf1a-bed8-4a0f-ba89-c604135474ed', 'addf5b8d-0a48-4954-894a-26b18aa4af72', 'Invest in the stock market safely', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('9aa9ebb7-138e-4459-af78-6539c9bc53db', '147080d8-8fb9-4e8f-b52f-b989ed560879', 'Which of these is a proper emergency-fund use?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b314b2c9-71ca-420a-895c-8e0796b363d4', '9aa9ebb7-138e-4459-af78-6539c9bc53db', 'An unexpected car repair', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6d06397e-3689-4b97-92f8-7e794cd40693', '9aa9ebb7-138e-4459-af78-6539c9bc53db', 'A limited-time sale on flights', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e98c4772-ef42-486f-947f-d139f20eb67b', '9aa9ebb7-138e-4459-af78-6539c9bc53db', 'Upgrading to the new iPhone', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('9fa39368-f81b-4f75-a45b-b6af40f8b461', 'b63b68ec-b31a-4174-85a4-d538ce92be4c', 'How Much Is Enough', '## How Much Is Enough

Two targets, in order:

1. **Starter fund: $500–$1,000.** Small, fast to reach, covers most common surprises (tire, copay, small repair).
2. **Full fund: 3–6 months of *essential* expenses.** Rent, food, utilities, minimum payments — not your full lifestyle. This is what protects you from a job loss.

**Where to keep it:** a high-yield savings account (HYSA). It must be:

- **Liquid** — accessible within a day or two
- **Boring** — not stocks; you can''t afford a 30% drop the week you need it
- **Separate** — a different account, so it doesn''t get spent casually', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('6b18b20f-3468-41de-b64e-2884b93dee98', '9fa39368-f81b-4f75-a45b-b6af40f8b461', 'A full emergency fund typically covers how many months of ESSENTIAL expenses?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6d600ef7-d521-44e7-9d27-1da0d30372f2', '6b18b20f-3468-41de-b64e-2884b93dee98', '3–6 months', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e3f3449c-c472-4c86-b4bd-f38a9d0d183c', '6b18b20f-3468-41de-b64e-2884b93dee98', '1–2 weeks', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('9ce4209e-59c4-4b12-8a86-7dcede3d085e', '6b18b20f-3468-41de-b64e-2884b93dee98', '10–12 months', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('9d03490f-c841-456e-8531-504d53c33eb6', '9fa39368-f81b-4f75-a45b-b6af40f8b461', 'Where should an emergency fund live?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('da4ccbf9-e77e-45c2-a533-a614a1665bbc', '9d03490f-c841-456e-8531-504d53c33eb6', 'A high-yield savings account, separate from spending money', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('530e62c6-ba8e-4aba-9252-b43d6d599a63', '9d03490f-c841-456e-8531-504d53c33eb6', 'Stock index funds, for growth', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6fdb52bb-addd-4de5-885f-59ac3524ea1c', '9d03490f-c841-456e-8531-504d53c33eb6', 'Your checking account, mixed with daily spending', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('3fb95df7-ea86-4db4-b59c-cde89efeafcc', 'understanding-debt', 'Understanding Debt', 4, 'b63b68ec-b31a-4174-85a4-d538ce92be4c');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('f297212f-1f82-4108-9290-195d6d56d676', '3fb95df7-ea86-4db4-b59c-cde89efeafcc', 'Good vs. Bad Debt', '## Good vs. Bad Debt

Debt isn''t automatically evil — the question is *what the borrowed money buys*:

- **Potentially good:** debt that buys an appreciating asset or earning power — a mortgage on a reasonable home, a student loan for a degree with real job prospects, a business loan for a proven plan.
- **Usually bad:** debt that funds consumption — credit card balances on dinners out, financing a vacation, payday loans for everyday bills.

Two rules of thumb:

1. Borrow for things that *outlast the loan*.
2. Never borrow at high interest for something that loses value (or is gone immediately).', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('2f4d3b82-5b40-4ab3-8027-95a3caa8bc2c', 'f297212f-1f82-4108-9290-195d6d56d676', 'Which is the BEST example of potentially good debt?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('87751b83-4688-4716-b7cd-1abe2b5d50bc', '2f4d3b82-5b40-4ab3-8027-95a3caa8bc2c', 'A student loan for a degree with strong job prospects', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('07d50c32-8b83-4536-ae29-a8a7a22272f9', '2f4d3b82-5b40-4ab3-8027-95a3caa8bc2c', 'A credit card balance from a vacation', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('516a9462-ba37-47f0-a281-f02267549514', '2f4d3b82-5b40-4ab3-8027-95a3caa8bc2c', 'A payday loan to cover this month''s bills', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('0a053b31-ed98-4475-931e-b75e7c30c535', 'f297212f-1f82-4108-9290-195d6d56d676', 'The key question for judging debt is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0beedcbf-f84a-4673-81b9-70270ca7810f', '0a053b31-ed98-4475-931e-b75e7c30c535', 'What does the borrowed money actually buy?', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('c9735ddc-dfe5-4980-a85c-1b077b1a31a2', '0a053b31-ed98-4475-931e-b75e7c30c535', 'Is the lender a big bank?', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a747cded-049d-41b1-9199-36829c3b6d17', '0a053b31-ed98-4475-931e-b75e7c30c535', 'Did a friend also take this loan?', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('657cb681-7dd1-455e-8d4a-c802b03eb085', '3fb95df7-ea86-4db4-b59c-cde89efeafcc', 'APR Basics', '## APR Basics

**APR (Annual Percentage Rate)** is the yearly cost of borrowing, as a percentage. A $1,000 balance at 24% APR costs about **$240/year** in interest.

Typical APR ranges:

- Payday loans: **300%+** (a $500 two-week loan can cost $75+ in fees)
- Credit cards: **20–30%**
- Auto loans: **5–10%**
- Mortgages: **3–7%**

**The minimum-payment trap:** card minimums are set barely above interest. Pay only the minimum on $3,000 at 24% and you''ll spend *years* paying it off — mostly interest. Always pay more than the minimum, and treat high-APR balances as your top priority after the starter emergency fund.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('fcee7336-bc60-49be-9b8d-b9331ff3f750', '657cb681-7dd1-455e-8d4a-c802b03eb085', 'Roughly how much interest per year does a $1,000 balance at 24% APR cost?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('201fb903-8ccf-405f-b96f-cb13d0894a64', 'fcee7336-bc60-49be-9b8d-b9331ff3f750', 'About $240', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('87c0fc92-b75d-4a7c-9355-331444b0256d', 'fcee7336-bc60-49be-9b8d-b9331ff3f750', 'About $24', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b6cc8697-af92-45df-acd6-e28853e8f9c2', 'fcee7336-bc60-49be-9b8d-b9331ff3f750', 'About $2,400', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('ef01aa02-f238-4bd4-9454-d5b2bad03f1d', '657cb681-7dd1-455e-8d4a-c802b03eb085', 'Why are payday loans considered dangerous?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('79c2efe4-826c-44e3-84b6-7c0191d6d8b9', 'ef01aa02-f238-4bd4-9454-d5b2bad03f1d', 'Their effective APRs can exceed 300%', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('80dc4ad8-dac4-4b5d-984b-ca20ffb6bcf3', 'ef01aa02-f238-4bd4-9454-d5b2bad03f1d', 'They require collateral like your house', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3e4726bf-7025-4be8-8fa3-f5edbf828f18', 'ef01aa02-f238-4bd4-9454-d5b2bad03f1d', 'They are always for larger amounts than credit cards', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('bf1a6155-7bf0-4ae8-a40c-447f7c6087bb', 'credit-scores', 'Credit Scores', 5, '3fb95df7-ea86-4db4-b59c-cde89efeafcc');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('0efdca0d-0e95-4194-b77d-6cff50b0f1ae', 'bf1a6155-7bf0-4ae8-a40c-447f7c6087bb', 'What Affects Your Score', '## What Affects Your Score

A credit score is a number (300–850) predicting how reliably you repay. The big factors:

- **Payment history (~35%)** — the single biggest one. One missed payment can hurt for years.
- **Credit utilization (~30%)** — how much of your limit you use. Keep it **under 30%**, lower is better.
- **Length of history (~15%)** — older accounts help; don''t close your oldest card without reason.
- **New credit (~10%)** — a burst of applications dings your score short-term.
- **Credit mix (~10%)** — variety helps slightly; don''t force it.

**The two levers that matter most:** pay every bill on time, and keep balances low relative to limits.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('4b61b890-94e9-4995-9110-9417f5a585c1', '0efdca0d-0e95-4194-b77d-6cff50b0f1ae', 'Which factor has the BIGGEST impact on a typical credit score?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('371c0ae0-4341-4c3f-a2b4-ddb6bbcb7fe4', '4b61b890-94e9-4995-9110-9417f5a585c1', 'Payment history', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('96270635-fcd1-4317-9854-7bdd94f6914f', '4b61b890-94e9-4995-9110-9417f5a585c1', 'Credit mix', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('adcc1ff2-6b6e-455f-abc0-da731290101a', '4b61b890-94e9-4995-9110-9417f5a585c1', 'Number of bank accounts', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('19782d30-40ba-4e29-aa4c-65e46c7908a5', '0efdca0d-0e95-4194-b77d-6cff50b0f1ae', 'As a rule of thumb, keep credit card utilization below...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('afe0a092-ea33-4984-bb7b-a3e48133f061', '19782d30-40ba-4e29-aa4c-65e46c7908a5', '30% of your limit', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e0dfbc58-fed6-46a2-aea6-329f8063d892', '19782d30-40ba-4e29-aa4c-65e46c7908a5', '90% of your limit', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('44b589d1-f758-4b79-aeee-09f646ab4b41', '19782d30-40ba-4e29-aa4c-65e46c7908a5', 'It doesn''t matter', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('483ab1b0-90ce-4a27-b2d9-444095ed7570', 'bf1a6155-7bf0-4ae8-a40c-447f7c6087bb', 'Why It Matters', '## Why It Matters

Your score follows you into more places than you''d expect:

- **Loans & cards:** a strong score can mean a mortgage at 6% instead of 8% — on a $300,000 loan, that''s **tens of thousands of dollars**.
- **Renting:** landlords often check credit; a weak score can mean a bigger deposit or a rejection.
- **Insurance & utilities:** many set prices or deposits partly on credit.
- **Jobs:** some employers check credit reports (not scores) for financial roles.

**The cheapest way to protect it:** automate at least the minimum payments on every account. On-time history builds itself; one missed payment undoes months of good behavior.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('3cc87a13-c9bf-4d6a-b0cb-b0ce776dbd2a', '483ab1b0-90ce-4a27-b2d9-444095ed7570', 'On a large mortgage, a better credit score can save you...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('27d9d301-f9b0-4400-ad79-e757ec4ea302', '3cc87a13-c9bf-4d6a-b0cb-b0ce776dbd2a', 'Tens of thousands of dollars in interest', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('32677984-1ce3-449e-a02b-8f5c8e0e00d4', '3cc87a13-c9bf-4d6a-b0cb-b0ce776dbd2a', 'Nothing — rates are fixed for everyone', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('999cc591-5008-4941-b5ad-2f88fec843e8', '3cc87a13-c9bf-4d6a-b0cb-b0ce776dbd2a', 'A few dollars a year', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('73331343-197e-480b-b53c-93311e3dda77', '483ab1b0-90ce-4a27-b2d9-444095ed7570', 'What''s the cheapest way to protect your credit score?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('16a1996e-cff2-47bb-85c6-a97d32400149', '73331343-197e-480b-b53c-93311e3dda77', 'Automate at least minimum payments on every account', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('8e17e01d-d1a8-474f-969e-e2f754c07bc2', '73331343-197e-480b-b53c-93311e3dda77', 'Close all your credit cards', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('98fab87c-f926-49ee-b009-b0d697d73990', '73331343-197e-480b-b53c-93311e3dda77', 'Apply for new credit often to show activity', 0, 2);
