-- Generated by worker/seed/generate-seed-sql.ts from worker/seed/units.json. Do not hand-edit.
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('3ae45438-338a-441e-87c6-721e6141ee36', 'paying-off-debt', 'Paying Off Debt', 6, 'bf1a6155-7bf0-4ae8-a40c-447f7c6087bb');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('b2556b9d-78b0-43f5-a566-dba109e116a9', '3ae45438-338a-441e-87c6-721e6141ee36', 'Avalanche vs. Snowball', '## Avalanche vs. Snowball

Two proven methods, one shared rule: pay the **minimum on every debt**, then throw every extra dollar at **one target**.

- **Avalanche:** attack the **highest APR** first. Mathematically optimal — you pay the least total interest.
- **Snowball:** attack the **smallest balance** first. Quick wins build momentum and motivation.

Avalanche saves the most money; snowball keeps the most people going. **The best method is the one you''ll actually finish** — follow-through matters more than interest-rate math.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('a92e7215-25a4-412d-a1b8-f620e3754c54', 'b2556b9d-78b0-43f5-a566-dba109e116a9', 'Which debt-payoff method targets the highest APR balance first?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('325859be-14fe-4f56-bed1-8fc5ce21747e', 'a92e7215-25a4-412d-a1b8-f620e3754c54', 'Avalanche', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('db3a2e57-1178-4416-b1ed-df68e2cc1180', 'a92e7215-25a4-412d-a1b8-f620e3754c54', 'Snowball', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('46bde240-8e9f-4d18-ab27-0cc8144db296', 'a92e7215-25a4-412d-a1b8-f620e3754c54', 'Debt consolidation', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('5dd5ec98-f59c-4a88-bc8e-6edf5106e5eb', 'b2556b9d-78b0-43f5-a566-dba109e116a9', 'The most important factor in choosing a payoff method is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('056f9be6-7a54-45c6-a082-b94225d9f290', '5dd5ec98-f59c-4a88-bc8e-6edf5106e5eb', 'Whether you''ll stick with it until the debts are gone', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('dbf3c583-128c-4b88-b475-e7377d1eed66', '5dd5ec98-f59c-4a88-bc8e-6edf5106e5eb', 'Which one sounds more impressive', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0312ca13-1ecf-424f-8523-00c5bd0f1219', '5dd5ec98-f59c-4a88-bc8e-6edf5106e5eb', 'Which one your bank prefers', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('58ddba3d-f1aa-4f10-86da-7ad4ff243489', '3ae45438-338a-441e-87c6-721e6141ee36', 'Getting Out Faster', '## Getting Out Faster

Free up extra money for the target debt:

1. Cancel subscription leaks (Unit 3).
2. Redirect windfalls — tax refunds, bonuses, gifts — straight to debt.
3. Sell things you no longer use.

**Watch the traps:**

- A 0% balance-transfer card can help, but the intro rate **expires** (then the APR jumps) and the transfer fee is 3–5%.
- Extra payments must go to **principal**, not future interest.
- Don''t close your oldest cards after paying them off — that shortens your credit history (Unit 6).', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('e3cf3693-27ef-4f56-8966-629f94cee79d', '58ddba3d-f1aa-4f10-86da-7ad4ff243489', 'A 0% balance-transfer card becomes a trap when...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e5ef9654-d299-42b9-b213-07eb095946ab', 'e3cf3693-27ef-4f56-8966-629f94cee79d', 'The intro rate expires and the APR jumps', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6a4cb363-f386-48d6-a47a-28c5bb3d96ea', 'e3cf3693-27ef-4f56-8966-629f94cee79d', 'It''s used to pay off a payday loan', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e935896d-2738-4152-8365-1b8c0a815c27', 'e3cf3693-27ef-4f56-8966-629f94cee79d', 'The credit limit is too high', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('bc260479-953b-4702-bca3-437cd310739b', '58ddba3d-f1aa-4f10-86da-7ad4ff243489', 'After paying off a credit card, you should generally...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ed910573-df06-4869-b4bf-09da4c2adc4b', 'bc260479-953b-4702-bca3-437cd310739b', 'Keep it open to preserve your credit history', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('9d515ad5-e52e-4aeb-848b-6b63f73e8773', 'bc260479-953b-4702-bca3-437cd310739b', 'Close it immediately', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b01a06ff-a1c5-4da0-9b05-3b274a3e71f6', 'bc260479-953b-4702-bca3-437cd310739b', 'Close your oldest card first', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('64a1a940-c0d9-4255-8554-86110accbb05', 'banking-basics', 'Banking Basics', 7, '3ae45438-338a-441e-87c6-721e6141ee36');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('d7e80f5d-b3b9-43bc-849a-26ee3dbce879', '64a1a940-c0d9-4255-8554-86110accbb05', 'Checking vs. Savings', '## Checking vs. Savings

- **Checking** — the spending account: debit card, bill pay, ATM access. Earns almost no interest, and that''s fine — its job is *flow*.
- **Savings** — the parking account: money you''re not spending soon. Its job is *growth* — and a **high-yield savings account (HYSA)** pays ~4% vs. ~0.01% at big traditional banks.

Both are **FDIC insured up to $250,000** per depositor per bank — the safest place money can live.

**Rule of thumb:** checking holds this month''s money; savings holds everything else.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('8d4aba62-8e2a-46e4-aac9-6e5e7fd1f932', 'd7e80f5d-b3b9-43bc-849a-26ee3dbce879', 'Which account is designed for daily spending and bills?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0778b73c-7244-4faa-ad38-f45ab33e3575', '8d4aba62-8e2a-46e4-aac9-6e5e7fd1f932', 'Checking', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('37b8262e-3e3a-4a02-95f1-aeba14baca31', '8d4aba62-8e2a-46e4-aac9-6e5e7fd1f932', 'A high-yield savings account', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('51bd9541-174e-4b1c-baa9-fd83a2504f68', '8d4aba62-8e2a-46e4-aac9-6e5e7fd1f932', 'A certificate of deposit', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('4edab673-084a-48a4-a382-6af7ff7ddbc7', 'd7e80f5d-b3b9-43bc-849a-26ee3dbce879', 'Why keep savings in an HYSA instead of a big-bank savings account?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6b9d4a88-bdc0-4e21-aefc-6b78e05373fd', '4edab673-084a-48a4-a382-6af7ff7ddbc7', 'HYSAs pay ~4% vs. ~0.01% — hundreds of times more interest', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('fe175d1a-a615-4a10-820b-6cb273316306', '4edab673-084a-48a4-a382-6af7ff7ddbc7', 'Big banks aren''t FDIC insured', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('05a5ef9c-2a99-4d26-91c0-879359072e18', '4edab673-084a-48a4-a382-6af7ff7ddbc7', 'HYSAs have unlimited withdrawals', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('0dc19b56-ba9e-487b-88c9-dc5874fdc997', '64a1a940-c0d9-4255-8554-86110accbb05', 'Fees to Avoid', '## Fees to Avoid

Bank fees are pure loss — and almost all avoidable:

- **Monthly maintenance fees** ($5–15) — usually waived with direct deposit or a minimum balance; if not, switch banks.
- **Overdraft fees** (~$35) — decline the "courtesy" overdraft so cards simply get declined instead.
- **Out-of-network ATM fees** ($3–5 each) — use in-network ATMs or a bank that rebates fees.
- **Foreign transaction fees** (1–3%) — pick a no-FX-fee card for travel.

A good bank today: **no monthly fee, no minimum, big ATM network**. Online banks check all three boxes.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('6c43fed4-7fb4-4152-a785-8ba009877ab4', '0dc19b56-ba9e-487b-88c9-dc5874fdc997', 'The most reliably avoidable bank fee is...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e393246d-cebb-4dce-b5bc-1071bbe0c1a9', '6c43fed4-7fb4-4152-a785-8ba009877ab4', 'The monthly maintenance fee — switch banks or meet the waiver', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e41faf26-bfcf-4d1f-b7b6-a99eddaebf92', '6c43fed4-7fb4-4152-a785-8ba009877ab4', 'FDIC insurance premiums', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('8bc9253b-8f0e-4def-9de5-f31fe72c7692', '6c43fed4-7fb4-4152-a785-8ba009877ab4', 'Interest earned on savings', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('264c0612-9b07-4bec-a12e-abb18dc3aafa', '0dc19b56-ba9e-487b-88c9-dc5874fdc997', 'If you opt out of overdraft "protection," a purchase you can''t afford will...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('7a48d49f-f3b9-477c-8c8c-aa2c80a4d2d8', '264c0612-9b07-4bec-a12e-abb18dc3aafa', 'Be declined — usually the better outcome', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('1c0fb1ae-2a58-43fa-9c9e-31f89fff99bc', '264c0612-9b07-4bec-a12e-abb18dc3aafa', 'Trigger a $35 fee anyway', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('c40f485b-6824-41d0-a60f-530aa1b254bd', '264c0612-9b07-4bec-a12e-abb18dc3aafa', 'Be paid by the government', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('c5df80b5-3dda-431c-a12a-2e7746f5f242', 'compound-interest', 'Compound Interest', 8, '64a1a940-c0d9-4255-8554-86110accbb05');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('8ce50344-2095-4b61-866a-b121a6b05f2a', 'c5df80b5-3dda-431c-a12a-2e7746f5f242', 'The Eighth Wonder', '## The Eighth Wonder

**Compound interest** means earning returns on your returns:

- Year 1: $100 grows 7% → $107
- Year 2: the *whole* $107 grows → $114.49
- Year 10: → ~$197. Year 20: → ~$387. Year 30: → ~$761

**The Rule of 72:** divide 72 by your annual return to estimate doubling time. At 7%, money doubles roughly every **10 years**.

The same force runs in reverse on debt: a credit-card balance at 24% APR doubles in about **3 years** if untouched. Compounding is the strongest force in personal finance — make sure it works *for* you.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f4acf18c-061a-47ff-8e43-233626a89568', '8ce50344-2095-4b61-866a-b121a6b05f2a', 'Using the Rule of 72, money invested at 8% doubles roughly every...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('cba378dc-b508-4092-bc34-af46c0c67a4f', 'f4acf18c-061a-47ff-8e43-233626a89568', '9 years', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('97c8b1f4-10f4-44ab-a717-cb52302709b4', 'f4acf18c-061a-47ff-8e43-233626a89568', '72 years', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('d5f67be6-0f68-4c77-8f47-1c87d43d0fa9', 'f4acf18c-061a-47ff-8e43-233626a89568', '3 years', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('7e8262c1-8cbf-42b8-bd09-47820349f402', '8ce50344-2095-4b61-866a-b121a6b05f2a', 'Compound interest works AGAINST you when you...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('5ca0d00d-26a8-4dc4-adae-9e0b3fa1b465', '7e8262c1-8cbf-42b8-bd09-47820349f402', 'Carry a high-interest balance', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('17578b4b-d49a-4fee-ad9d-b72d5c0757a6', '7e8262c1-8cbf-42b8-bd09-47820349f402', 'Save in an HYSA', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('605bbac0-39cf-4445-87ae-8b91c7f171a4', '7e8262c1-8cbf-42b8-bd09-47820349f402', 'Hold index funds for decades', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('9919e5f0-5f2f-44b5-8a59-f5afd0c30e62', 'c5df80b5-3dda-431c-a12a-2e7746f5f242', 'Time Is the Multiplier', '## Time Is the Multiplier

Two people invest $200/month at a 7% average return until age 65:

- **Starts at 25:** contributes $96,000 → ends with **~$525,000**
- **Starts at 35:** contributes $72,000 → ends with **~$244,000**

The 10-year head start more than *doubles* the final result — the early dollars do the heaviest lifting because they compound longest.

**The takeaway:** you can''t get time back. The most valuable thing a young investor has is *years* — and the second-best day to start is today.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f2d1a795-feb8-4822-bbf9-974d2ee49ab7', '9919e5f0-5f2f-44b5-8a59-f5afd0c30e62', 'Two people save $200/month at 7% until 65 — one from age 25, one from 35. Who ends with more?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('bd25c63b-6e16-41bf-84b7-46976695c185', 'f2d1a795-feb8-4822-bbf9-974d2ee49ab7', 'The one who started at 25 — by more than double', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e68f9c74-0340-413a-9bc4-d94d2e8b4680', 'f2d1a795-feb8-4822-bbf9-974d2ee49ab7', 'The one who started at 35 — bigger contributions', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6195f366-df0e-4efe-b76b-e6cb40447fda', 'f2d1a795-feb8-4822-bbf9-974d2ee49ab7', 'Roughly the same', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('a339812d-1fc6-4385-833b-74206cf38746', '9919e5f0-5f2f-44b5-8a59-f5afd0c30e62', 'The most powerful input to compound growth is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('59334d8f-877f-40cb-b6e0-31f69bea8846', 'a339812d-1fc6-4385-833b-74206cf38746', 'Time in the market', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('8a674387-a4ea-4dbb-a080-a6500948259e', 'a339812d-1fc6-4385-833b-74206cf38746', 'Picking hot stocks', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3c979e4c-4f00-4304-ab47-93a717ad7943', 'a339812d-1fc6-4385-833b-74206cf38746', 'Checking prices daily', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('8e3b3287-5e6f-4207-a54d-f0215e1197b5', 'inflation', 'Inflation', 9, 'c5df80b5-3dda-431c-a12a-2e7746f5f242');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('b68dc09d-1a35-4c62-abde-e9b98d72cbf1', '8e3b3287-5e6f-4207-a54d-f0215e1197b5', 'Why Cash Loses Value', '## Why Cash Loses Value

**Inflation** means prices rise over time — each dollar buys a little less every year. US inflation has averaged ~3% annually: at that pace, $100 buys about **$97** of goods next year and ~$74 in ten years.

That''s why the mattress is the riskiest place for long-term money: it''s *guaranteed* to lose purchasing power.

**Real return** is what''s left after inflation:

> Real return = Nominal return − Inflation

A savings account paying 1% with 3% inflation has a **−2% real return** — a slow, silent loss.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('5152eed7-7c9e-4f5c-8fda-ed19751c5fd6', 'b68dc09d-1a35-4c62-abde-e9b98d72cbf1', 'Real return is calculated as...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f8946d81-f0af-4f82-99aa-fe2e7e6d2cc0', '5152eed7-7c9e-4f5c-8fda-ed19751c5fd6', 'Nominal return minus inflation', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0df7a479-0ee7-4f9e-8836-573acb69a039', '5152eed7-7c9e-4f5c-8fda-ed19751c5fd6', 'Nominal return plus inflation', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('cf633819-faee-410f-b342-f10e3e996dd4', '5152eed7-7c9e-4f5c-8fda-ed19751c5fd6', 'Nominal return times two', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('74a31ea6-9f64-48f7-be6e-ba19cdffb296', 'b68dc09d-1a35-4c62-abde-e9b98d72cbf1', 'Your savings pay 1% while inflation runs 3%. Your real return is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('912e6b7b-30ff-4672-96e5-214320941fbd', '74a31ea6-9f64-48f7-be6e-ba19cdffb296', '−2% — you''re slowly losing purchasing power', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ff22007b-b0e4-4419-8e41-d38e7d7b33b8', '74a31ea6-9f64-48f7-be6e-ba19cdffb296', '+4%', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('05016dd4-ed6e-433d-8d21-05809cda031a', '74a31ea6-9f64-48f7-be6e-ba19cdffb296', '+1% — you break even', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('0f7b521d-df01-4d88-b3ff-1f5080f1664b', '8e3b3287-5e6f-4207-a54d-f0215e1197b5', 'Beating Inflation', '## Beating Inflation

To *grow* purchasing power, your after-fee, after-tax return must beat inflation:

- **Cash / checking (0–1%):** loses to inflation, always
- **HYSAs (~4%):** usually keeps pace
- **Stocks (~10% nominal / ~7% real long-run average):** historically the reliable long-term winner

This is why long-horizon money gets **invested**, not saved — investing isn''t about getting rich; it''s about not getting poorer.

**The exception:** your emergency fund. Its job is instant access and zero risk, not growth — a small real loss is the fair price of that safety.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('13e4f984-d39a-4e18-9327-18647786963a', '0f7b521d-df01-4d88-b3ff-1f5080f1664b', 'Over the long run, which has most reliably beaten inflation?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('4e6cc91c-8c4a-4e37-9084-bdd7932d4360', '13e4f984-d39a-4e18-9327-18647786963a', 'Stocks', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('2a2c4064-c2e1-4be9-9721-5c1208004c83', '13e4f984-d39a-4e18-9327-18647786963a', 'Checking accounts', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e02cd6a6-de8d-4077-b35e-470e7c7209fa', '13e4f984-d39a-4e18-9327-18647786963a', 'Cash under the mattress', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('eb2f7b4d-2d39-4d14-9906-68d6f5d89f6c', '0f7b521d-df01-4d88-b3ff-1f5080f1664b', 'Why doesn''t the emergency fund need to beat inflation?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('26c490f4-ffa5-47d9-9dd3-4268d7e65331', 'eb2f7b4d-2d39-4d14-9906-68d6f5d89f6c', 'Its job is instant access and safety, not growth', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f5fc3cd4-6c78-45e8-af9a-d3836b000686', 'eb2f7b4d-2d39-4d14-9906-68d6f5d89f6c', 'Inflation ignores small balances', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('85ec5c8f-d926-4299-ba09-98cc41f13984', 'eb2f7b4d-2d39-4d14-9906-68d6f5d89f6c', 'FDIC insurance covers inflation', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('1cc0a6a2-a800-4419-a435-1bee460bc573', 'investing-basics', 'Investing Basics', 10, '8e3b3287-5e6f-4207-a54d-f0215e1197b5');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('9ddf8fc7-28fd-4bef-baf3-37ca9c365454', '1cc0a6a2-a800-4419-a435-1bee460bc573', 'Stocks, Bonds, Funds', '## Stocks, Bonds, Funds

The three building blocks:

- **Stock** — a tiny ownership slice of a company. Returns come from growth and dividends; prices swing hard.
- **Bond** — a *loan* to a company or government. It pays fixed interest and ranks ahead of stockholders if things go wrong: steadier, lower returns.
- **Fund (ETF / mutual fund)** — a basket of hundreds of stocks and/or bonds in one purchase: instant diversification.

**Risk ↔ return:** higher potential return always comes with higher potential loss. There is no high-return, no-risk asset — anyone promising one is selling something else.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('d6ebb902-2265-43a7-8419-1acf4619534e', '9ddf8fc7-28fd-4bef-baf3-37ca9c365454', 'Owning one share of stock means you...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('44d97bf1-c5ac-4291-a647-56e666f62022', 'd6ebb902-2265-43a7-8419-1acf4619534e', 'Own a small piece of that company', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e51e3835-1bb8-4ffe-8fe7-5042a6cc39f9', 'd6ebb902-2265-43a7-8419-1acf4619534e', 'Lent the company money', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a625c491-aed9-4695-b487-a759da699bab', 'd6ebb902-2265-43a7-8419-1acf4619534e', 'Are guaranteed a payout', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('69ccff0d-06bc-4224-a0e0-7eb690675261', '9ddf8fc7-28fd-4bef-baf3-37ca9c365454', 'Compared to a single stock, a fund is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('439d96e6-bb18-4d25-b0c1-95523d3185d3', '69ccff0d-06bc-4224-a0e0-7eb690675261', 'Less risky because it spreads money across many holdings', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('9d016a9d-3e71-49c6-ac9c-31657c09c973', '69ccff0d-06bc-4224-a0e0-7eb690675261', 'More risky because it holds more things', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6914b79a-f539-4fa0-a983-33fc70052f9c', '69ccff0d-06bc-4224-a0e0-7eb690675261', 'Guaranteed by the government', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('31d163b4-d05c-4b3a-a017-aec1a4699a34', '1cc0a6a2-a800-4419-a435-1bee460bc573', 'Risk vs. Return', '## Risk vs. Return

The risk ladder (long-run averages, not promises):

- **Savings / HYSAs:** 0–4%, essentially no risk (FDIC)
- **Bonds:** 2–5%, mild swings
- **Stocks:** ~7–10% average, with years of −30%+ on the way

**Your time horizon picks your rung.** Money you need within ~3–5 years (emergency fund, next year''s tuition, a down payment) doesn''t belong in stocks — a bad year right before you need it is a loss you can''t wait out. Long-horizon money (retirement) can ride out the swings and should take the growth.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('b7d9642d-149f-4c3e-89ff-770addae4749', '31d163b4-d05c-4b3a-a017-aec1a4699a34', 'Money you need for a down payment next year should be...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('873c6547-bce7-43ee-83c3-8f5fd3622159', 'b7d9642d-149f-4c3e-89ff-770addae4749', 'In safe, liquid accounts — not stocks', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ca3868e9-383f-483d-80e8-45b23812eeeb', 'b7d9642d-149f-4c3e-89ff-770addae4749', 'In individual tech stocks', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('613f9129-c23f-4efb-ac3d-3402d7609d0c', 'b7d9642d-149f-4c3e-89ff-770addae4749', 'In crypto for the upside', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('16ae22f9-fc46-4179-9453-055cd1db9da2', '31d163b4-d05c-4b3a-a017-aec1a4699a34', '"Higher expected return" in investing always comes with...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('68addfec-cf8b-467a-a170-c2f36c1f1af7', '16ae22f9-fc46-4179-9453-055cd1db9da2', 'Higher risk of loss', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('740394cf-bd04-46ef-bf23-945b76c4ae0c', '16ae22f9-fc46-4179-9453-055cd1db9da2', 'A government guarantee', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e6f08d30-bef2-4f31-9107-5c8d1bef16cd', '16ae22f9-fc46-4179-9453-055cd1db9da2', 'FDIC insurance', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('8b511cb0-f2ac-44df-a15e-0c62dc8a780f', 'index-funds-diversification', 'Index Funds & Diversification', 11, '1cc0a6a2-a800-4419-a435-1bee460bc573');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('ddcc368f-5033-464c-94c8-b7caed07b163', '8b511cb0-f2ac-44df-a15e-0c62dc8a780f', 'Why Index Funds', '## Why Index Funds

An **index fund** doesn''t try to pick winners — it just owns the whole market (e.g., all 500 S&P 500 companies). You get average market returns, which beat most professionals:

- **Low fees:** ~0.03–0.2% per year vs. 1%+ for many actively managed funds
- **Better odds:** over 15+ years, roughly 90% of active funds underperform their index
- **Zero skill required:** no research, no timing, no stock-picking luck needed

Fees compound *against* you exactly like returns compound for you: 1% extra in fees over 30 years can eat **a quarter or more** of your final balance.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('0390398b-48e1-4b05-9454-d677c9810b7f', 'ddcc368f-5033-464c-94c8-b7caed07b163', 'An S&P 500 index fund holds...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('5fe404a5-8e12-487c-81ad-37f5ee9131cb', '0390398b-48e1-4b05-9454-d677c9810b7f', 'All (or most) of the 500 largest US companies', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('8717bcd3-7299-456f-84d2-4d0ee3b1521b', '0390398b-48e1-4b05-9454-d677c9810b7f', 'The 5 hottest stocks', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3239916c-6bfd-43c2-9044-e538c3fee72b', '0390398b-48e1-4b05-9454-d677c9810b7f', 'Only companies that beat the market', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f34e810c-c3a2-4d0a-84b8-d2dedabe0bef', 'ddcc368f-5033-464c-94c8-b7caed07b163', 'Why do fund fees matter so much?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3507f5c4-ead7-4332-b5b2-3966f3251988', 'f34e810c-c3a2-4d0a-84b8-d2dedabe0bef', 'They compound against you every single year', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f32bef32-75ed-4c87-ad11-1896d050298e', 'f34e810c-c3a2-4d0a-84b8-d2dedabe0bef', 'They''re only charged on losses', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('4b2a8f1b-82c8-4788-83db-4d94e1eec32a', 'f34e810c-c3a2-4d0a-84b8-d2dedabe0bef', 'They''re refunded at retirement', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('eae678dc-f5e8-43d9-a383-8270139bb43f', '8b511cb0-f2ac-44df-a15e-0c62dc8a780f', 'Don''t Pick Stocks', '## Don''t Pick Stocks

Picking stocks that beat the market, consistently, is nearly impossible — most professionals fail at it, and one company can go to **zero** (Enron, Lehman) while the market as a whole has always recovered.

**Time in the market beats timing the market.** Missing just the 10 best days over a few decades can cut your total return roughly in half — and the best days cluster right after the worst ones, exactly when selling feels safest.

The whole strategy in one sentence: **buy a total-market index fund, automatically, every month, for decades, and ignore the noise.**', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f9e77bfc-fa6b-4713-b2a2-1af3994ba2dd', 'eae678dc-f5e8-43d9-a383-8270139bb43f', '"Time in the market beats timing the market" means...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('29626bc7-7140-4956-a664-ffed6408a0aa', 'f9e77bfc-fa6b-4713-b2a2-1af3994ba2dd', 'Staying invested long-term beats trying to buy and sell at perfect moments', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6197f305-89e0-4f39-b59b-0c58a5a9b7f8', 'f9e77bfc-fa6b-4713-b2a2-1af3994ba2dd', 'Day trading is the fastest path to wealth', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3aea8b67-57a2-4ee9-8882-b081b13cdaee', 'f9e77bfc-fa6b-4713-b2a2-1af3994ba2dd', 'Wait for a crash before investing', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('ea470200-4de8-4005-ae2e-408a3a4fb862', 'eae678dc-f5e8-43d9-a383-8270139bb43f', 'The key danger of holding a single company''s stock is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e761ebef-515e-4c63-8aa5-30f58849e4ea', 'ea470200-4de8-4005-ae2e-408a3a4fb862', 'One company can fail while the whole market recovers', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6e11c6f3-424a-46a3-a165-b7241d193e5b', 'ea470200-4de8-4005-ae2e-408a3a4fb862', 'Stocks never recover after drops', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f0c0e685-5d5a-404f-9db1-9c6e4058f3a5', 'ea470200-4de8-4005-ae2e-408a3a4fb862', 'Dividends are illegal', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('4f1daae3-67cf-4909-be1d-fbc3ba7b0d73', 'retirement-accounts', 'Retirement Accounts', 12, '8b511cb0-f2ac-44df-a15e-0c62dc8a780f');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('aeee0a08-5eba-4c5d-8092-df1fe402bbd8', '4f1daae3-67cf-4909-be1d-fbc3ba7b0d73', 'Tax-Advantaged Accounts', '## Tax-Advantaged Accounts

Retirement accounts (401(k), IRA, or your country''s equivalents) are special wrappers around the same index funds — with a superpower: **investments inside them compound without yearly tax drag.**

- **Traditional:** contributions reduce taxable income *now*; withdrawals are taxed later.
- **Roth:** contributions are taxed *now*; qualified withdrawals are **tax-free forever**.

Either way, decades of untaxed compounding is the single biggest legal boost available to a normal investor.

The trade-offs: annual contribution limits, and withdrawals before retirement age usually owe penalties (with exceptions).', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('c14134b2-2a09-4dc2-a3da-3ad8f248b04a', 'aeee0a08-5eba-4c5d-8092-df1fe402bbd8', 'The key benefit of investing inside a retirement account is...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('974ffa28-2581-40c4-b436-7e6e69440834', 'c14134b2-2a09-4dc2-a3da-3ad8f248b04a', 'Decades of compounding without yearly tax drag', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6db37fae-1bb1-44ec-9f0b-68412c94630b', 'c14134b2-2a09-4dc2-a3da-3ad8f248b04a', 'Guaranteed investment returns', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('49856c3e-f8f8-474f-9beb-ebd5647b6cf8', 'c14134b2-2a09-4dc2-a3da-3ad8f248b04a', 'Higher interest rates from banks', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('e0b5bc6a-3d00-484e-ac69-adcba0512e3b', 'aeee0a08-5eba-4c5d-8092-df1fe402bbd8', 'With a Roth-style account, taxes are paid...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('d26710cb-c92b-4d19-87e6-09962e22ebf4', 'e0b5bc6a-3d00-484e-ac69-adcba0512e3b', 'Now — and qualified withdrawals come out tax-free', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('baef35b3-d3bd-4cd9-b960-6fb7ea8d627f', 'e0b5bc6a-3d00-484e-ac69-adcba0512e3b', 'Never at all', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a8c31d56-b1c1-464e-885a-4c44cf346ea2', 'e0b5bc6a-3d00-484e-ac69-adcba0512e3b', 'Only after age 65', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('ae3aec4f-9ee8-40cd-b7b4-b4fb5a081125', '4f1daae3-67cf-4909-be1d-fbc3ba7b0d73', 'The Employer Match', '## The Employer Match

Many employers match 401(k) contributions — e.g., **50 cents per dollar up to 6% of salary**. That match is an **instant 50% return** on every matched dollar. Nothing else in investing reliably offers that.

**Priority order for each paycheck:**

1. Capture the **full employer match** (free money first)
2. Kill **high-interest debt** (24% APR beats 7% returns)
3. Fill retirement accounts
4. Taxable investing / other goals

Leaving a match unclaimed is declining part of your own salary — it''s the most expensive mistake in personal finance.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('d023a486-0f4d-4905-9e12-eb086b56f62d', 'ae3aec4f-9ee8-40cd-b7b4-b4fb5a081125', 'A 50% match on contributions is effectively...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('7fc6f2d5-b4b9-419a-a98d-cd0dae42543b', 'd023a486-0f4d-4905-9e12-eb086b56f62d', 'An instant 50% return on matched money', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a55cf3f9-422e-4626-bfb4-9ba793a001b1', 'd023a486-0f4d-4905-9e12-eb086b56f62d', 'A loan you must repay', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('fb50325c-cf55-4f6c-be40-0bef5f352a13', 'd023a486-0f4d-4905-9e12-eb086b56f62d', 'A tax on your salary', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('18e19370-e2aa-44ef-a710-0b1a227a3ef4', 'ae3aec4f-9ee8-40cd-b7b4-b4fb5a081125', 'Why capture the full match before other investing?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('253f59ae-1815-4d00-8754-601f92786815', '18e19370-e2aa-44ef-a710-0b1a227a3ef4', 'No other investment reliably returns 50% instantly', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0701fc50-b4cd-4edd-82e1-5cadb03574a9', '18e19370-e2aa-44ef-a710-0b1a227a3ef4', 'Matches are FDIC insured', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('eb73208e-50f3-48f6-8520-5006d199a1c8', '18e19370-e2aa-44ef-a710-0b1a227a3ef4', 'It eliminates your tax bill', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('1e84945a-2120-4119-a10e-be014e4910cf', 'taxes-101', 'Taxes 101', 13, '4f1daae3-67cf-4909-be1d-fbc3ba7b0d73');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('c9f59364-3416-4f0b-989e-3bec151d8b25', '1e84945a-2120-4119-a10e-be014e4910cf', 'How Income Is Taxed', '## How Income Is Taxed

Tax brackets are **marginal**: each slice of income is taxed at its own rate — moving into a higher bracket only taxes the *extra* dollars at the higher rate, never your whole income.

Example (simplified): if 10% applies to your first $11,000 and 12% above it, a raise from $11,000 to $12,000 pays 12% only on the last $1,000.

**Take-home pay** = gross − federal/state income tax − payroll tax (FICA ~7.65%) − pre-tax deductions. Budget from take-home, never gross — and know your **effective rate** (total tax ÷ total income), which is always lower than your top bracket.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('dd0542c6-9c91-4e22-8662-c16543087c68', 'c9f59364-3416-4f0b-989e-3bec151d8b25', 'You move into a higher tax bracket. What happens?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('546d14d1-edf1-42a6-b685-5c3734082f93', 'dd0542c6-9c91-4e22-8662-c16543087c68', 'Only the income above the threshold is taxed at the higher rate', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('95ee1c4d-8d10-44c1-a588-4a81649ec3a7', 'dd0542c6-9c91-4e22-8662-c16543087c68', 'All your income is taxed at the higher rate', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('aba5c670-af93-4f76-a87e-5237d16d04a6', 'dd0542c6-9c91-4e22-8662-c16543087c68', 'You owe back taxes on prior years', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('b83a41dd-928c-406f-9a9b-83649d2f5ae9', 'c9f59364-3416-4f0b-989e-3bec151d8b25', 'Your effective tax rate is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('77f49c82-5b3d-484b-98dc-a39b51ec6e59', 'b83a41dd-928c-406f-9a9b-83649d2f5ae9', 'Total tax ÷ total income', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b36c94b8-23e9-4144-b19f-dbb13378d942', 'b83a41dd-928c-406f-9a9b-83649d2f5ae9', 'The rate of your top bracket', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('39509fed-b759-4751-aee1-1c8c8807f0eb', 'b83a41dd-928c-406f-9a9b-83649d2f5ae9', 'The same for everyone', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('8bbfbdec-bac3-47a0-87f4-c45cbf2c42ca', '1e84945a-2120-4119-a10e-be014e4910cf', 'Keeping More of Your Pay', '## Keeping More of Your Pay

Legal ways to lower the bill:

- **Pre-tax deductions** (traditional 401(k), HSA, some insurance premiums) shrink taxable income while building wealth.
- **Credits beat deductions:** a **credit** cuts tax owed dollar-for-dollar; a **deduction** only removes taxable income. A $1,000 credit saves $1,000; a $1,000 deduction saves maybe $220.
- **A huge refund every year** means you over-withheld — an interest-free loan to the government. Adjust your withholding and put the difference to work monthly instead.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('9ff1b7d0-d419-4168-9de8-656f7357eb23', '8bbfbdec-bac3-47a0-87f4-c45cbf2c42ca', 'Which reduces your tax bill dollar-for-dollar?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('c9060288-2d0f-47f9-b60d-c4ca800ef073', '9ff1b7d0-d419-4168-9de8-656f7357eb23', 'A tax credit', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a8f105ce-1cc3-434d-8d35-96c23a4594ba', '9ff1b7d0-d419-4168-9de8-656f7357eb23', 'A tax deduction', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('de1b4654-b8dc-45b9-a658-c3b26321a42d', '9ff1b7d0-d419-4168-9de8-656f7357eb23', 'A higher tax bracket', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f590bac7-ac92-4ffd-9232-b5ed482d02fd', '8bbfbdec-bac3-47a0-87f4-c45cbf2c42ca', 'A big tax refund every year usually means...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('fc97e0e1-b627-4fc9-a75f-4080ba335de2', 'f590bac7-ac92-4ffd-9232-b5ed482d02fd', 'You over-withheld — an interest-free loan to the government', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('599378e8-6dd0-4439-a384-69bee7ad7e9e', 'f590bac7-ac92-4ffd-9232-b5ed482d02fd', 'You''re maximizing wealth', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('d0f0b60f-578f-4406-b3e8-dfbdb9f50b65', 'f590bac7-ac92-4ffd-9232-b5ed482d02fd', 'An audit is coming', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('54481e55-0197-467e-bdfd-4fe78d8ddeb4', 'insurance-basics', 'Insurance Basics', 14, '1e84945a-2120-4119-a10e-be014e4910cf');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('5c9b78d6-326a-4337-b457-21cf2c777723', '54481e55-0197-467e-bdfd-4fe78d8ddeb4', 'What Insurance Actually Is', '## What Insurance Actually Is

Insurance is **risk transfer**: thousands of people pay small premiums so that the unlucky few aren''t financially destroyed. You''re not betting on disaster — you''re buying protection from the *catastrophic* version of it.

- **Premium:** what you pay (monthly/yearly)
- **Deductible:** what you pay out of pocket before coverage kicks in

**The rule:** insure what you *can''t afford* to lose (health disaster, house fire, liability lawsuit); self-insure the small stuff (phone screens, minor repairs) with your emergency fund. Extended warranties on gadgets are usually insurance you don''t need, at a price that''s pure profit for the seller.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('8149953f-4f64-4c54-8552-ba0e7d7a6b58', '5c9b78d6-326a-4337-b457-21cf2c777723', 'The core purpose of insurance is to...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('dd96017e-8800-4abe-a0a0-6417eaf5ce62', '8149953f-4f64-4c54-8552-ba0e7d7a6b58', 'Transfer the cost of rare, unaffordable disasters', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('16fa1ffa-ec60-42e9-a1ea-9712bcba95bc', '8149953f-4f64-4c54-8552-ba0e7d7a6b58', 'Make a profit on premiums', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3084fd32-9dfd-47ed-9ce1-cfd32d62acbf', '8149953f-4f64-4c54-8552-ba0e7d7a6b58', 'Cover small predictable expenses', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('783b9c91-533f-4f9b-b3a9-a19d44b90858', '5c9b78d6-326a-4337-b457-21cf2c777723', 'A deductible is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('5388349c-7949-420d-8ca0-bad47b6cf1b3', '783b9c91-533f-4f9b-b3a9-a19d44b90858', 'What you pay out of pocket before coverage starts', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b2140ab3-d07c-44f3-970e-e1baa609d74d', '783b9c91-533f-4f9b-b3a9-a19d44b90858', 'The insurer''s profit margin', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('fa48947c-e7e1-43a1-b2f1-fd303d40d174', '783b9c91-533f-4f9b-b3a9-a19d44b90858', 'A monthly subscription fee', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('3e6b2662-21da-4000-9c81-8ed19fb99a3c', '54481e55-0197-467e-bdfd-4fe78d8ddeb4', 'Coverage You Probably Need', '## Coverage You Probably Need

- **Health** — the #1 cause of US bankruptcies; even a basic plan caps catastrophe.
- **Auto liability** — legally required, and one at-fault crash can dwarf any premium.
- **Renters** — ~$15/month, covers your belongings *and* liability if someone is injured in your place.
- **Term life** — if anyone depends on your income: ~10–12× your salary, for a fraction of what whole life costs.
- **Disability** — protects your *paycheck*, your biggest asset.

**Usually skip:** extended warranties, flight insurance, and whole-life policies sold as "investments" — high fees wrapped in insurance you don''t need.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('e213b2a9-0ebf-401a-8d85-f5c8dfc8222a', '3e6b2662-21da-4000-9c81-8ed19fb99a3c', 'Who most needs term life insurance?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('21c20a8b-d43f-4298-97bb-5f5282edfea4', 'e213b2a9-0ebf-401a-8d85-f5c8dfc8222a', 'People whose dependents rely on their income', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3e8522ef-90fe-438f-b168-edf0fa7778bd', 'e213b2a9-0ebf-401a-8d85-f5c8dfc8222a', 'Single people with no dependents', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('c3d7a492-ef87-4195-9be9-bdfdb0101605', 'e213b2a9-0ebf-401a-8d85-f5c8dfc8222a', 'Only retirees', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f72a72a3-e899-4191-a253-96bb02eada23', '3e6b2662-21da-4000-9c81-8ed19fb99a3c', 'Which is usually NOT worth the price?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ca5a12ac-eaca-4d34-97cd-91d846d97322', 'f72a72a3-e899-4191-a253-96bb02eada23', 'Extended warranties on gadgets', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('23936c6a-60e6-46ed-8a27-30c60bb516cb', 'f72a72a3-e899-4191-a253-96bb02eada23', 'Renters insurance', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('15dd93a1-00cc-4da9-954e-0a41a8b4f955', 'f72a72a3-e899-4191-a253-96bb02eada23', 'Auto liability coverage', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('ac53bc04-2121-4ffe-a768-67eee7b14828', 'big-purchases', 'Big Purchases', 15, '54481e55-0197-467e-bdfd-4fe78d8ddeb4');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('199986aa-acb9-40ff-9019-48dbe2bd783f', 'ac53bc04-2121-4ffe-a768-67eee7b14828', 'Buying a Car', '## Buying a Car

New cars lose roughly **20% of their value in the first year** and about half within five. The cheapest move: buy **reliable used (2–3 years old)** and let the first owner absorb the steepest depreciation.

Budget the **total cost of ownership**, not the payment: insurance, fuel, maintenance, registration, and loan interest.

A common affordability guideline — the **20/4/10 rule**: at least 20% down, a loan no longer than 4 years, and total car costs under ~10% of take-home pay. A longer loan lowers the payment but often leaves you owing more than the car is worth.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f5a3cdc8-e2ec-4bbb-852d-7b3191b318d6', '199986aa-acb9-40ff-9019-48dbe2bd783f', 'A new car typically loses about what share of its value in the first year?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e0afe0d5-3012-481a-b667-9d4ba66011b4', 'f5a3cdc8-e2ec-4bbb-852d-7b3191b318d6', '~20%', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('9dbb007f-5e8a-4d70-942e-9b4f1b56a329', 'f5a3cdc8-e2ec-4bbb-852d-7b3191b318d6', '~2%', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3021de26-c392-4ea0-9ab7-7da57a2b2eb0', 'f5a3cdc8-e2ec-4bbb-852d-7b3191b318d6', '~75%', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('4280688d-f653-4f86-8f3c-b824262249c0', '199986aa-acb9-40ff-9019-48dbe2bd783f', 'The 20/4/10 guideline suggests...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ac5adff4-bda8-405a-95fa-6332bf52bf68', '4280688d-f653-4f86-8f3c-b824262249c0', '20% down, ≤4-year loan, car costs ≤10% of take-home pay', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('cade0b8d-fba8-4f2d-b7ad-376c4c6ab8e2', '4280688d-f653-4f86-8f3c-b824262249c0', '$20k price, 4 doors, 10 mpg', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('2d79b34c-3b9f-45d3-bbd4-5248084afe79', '4280688d-f653-4f86-8f3c-b824262249c0', '20 cars, 4 years, 10 owners', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('28162d0e-232d-4d67-97bc-5f051f30ffad', 'ac53bc04-2121-4ffe-a768-67eee7b14828', 'Rent vs. Buy', '## Rent vs. Buy

**Renting is not wasted money.** It buys flexibility, zero maintenance risk, and freedom to relocate — often the right call for anyone who might move within ~5 years.

Buying makes sense when you''ll **stay 5+ years**, have stable income, a full emergency fund, and a total cost (mortgage + property tax + insurance + maintenance) that fits comfortably. Beyond the mortgage, budget maintenance at roughly **1–2% of the home''s value per year**, on top of property taxes and insurance.

A home is a *leveraged, illiquid, concentrated* bet on one property in one neighborhood. Buy it for stability and life fit — not as a guaranteed investment.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('b16e6f96-a2b5-464b-a430-04103ecaa697', '28162d0e-232d-4d67-97bc-5f051f30ffad', 'Renting is often the right call when...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('492d34bb-5a09-4cf3-8614-e1bf8a9da133', 'b16e6f96-a2b5-464b-a430-04103ecaa697', 'You might move within about five years', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('29ade236-1a4c-405c-8bf9-71e4a6f0033e', 'b16e6f96-a2b5-464b-a430-04103ecaa697', 'You want maximum leverage', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ff45f148-a5a0-4a42-b3cd-cf2d7e1e2d00', 'b16e6f96-a2b5-464b-a430-04103ecaa697', 'Rents are rising fast', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('3b3bfbfa-dea9-4244-88f9-cf7a460b597b', '28162d0e-232d-4d67-97bc-5f051f30ffad', 'Beyond the mortgage, yearly maintenance alone typically costs about what % of a home''s value?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('26a42d9c-0fa5-4194-ac43-af6b7802e782', '3b3bfbfa-dea9-4244-88f9-cf7a460b597b', '~1–2%', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('7c10460f-9563-49ae-99cb-5940fb6a080e', '3b3bfbfa-dea9-4244-88f9-cf7a460b597b', '~25%', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('68283bbd-9e7e-4ce5-b8e0-8c4acd4d7326', '3b3bfbfa-dea9-4244-88f9-cf7a460b597b', '~0% — the mortgage covers it', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('62dd220a-87ed-4c8b-ae97-52a2865a8520', 'side-income-negotiation', 'Side Income & Negotiation', 16, 'ac53bc04-2121-4ffe-a768-67eee7b14828');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('48ef9524-bd0b-4876-b80b-eec76e7937d4', '62dd220a-87ed-4c8b-ae97-52a2865a8520', 'Raising Your Income', '## Raising Your Income

Cutting expenses has a floor; income doesn''t. The highest-ROI moves, in order:

1. **Negotiate your salary** — one conversation raises the base for *every* future raise and bonus.
2. **Switch employers** — job-switchers often land +10–20% vs. ~3–4% for those who stay.
3. **Build in-demand skills** — the market pays for scarce abilities.
4. **Side income** — freelance what you already do; watch for **self-employment tax** (set aside ~25–30% of profit).

A $5,000 raise negotiated once at 25 compounds through every subsequent raise — the same math as Unit 9, applied to your paycheck.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('7aaf94d5-cd5a-4f26-8bc6-3fa47f5ce12f', '48ef9524-bd0b-4876-b80b-eec76e7937d4', 'Why is salary negotiation such a high-ROI move?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('445a25d1-e7c1-412c-9d9e-4a42f2c67bff', '7aaf94d5-cd5a-4f26-8bc6-3fa47f5ce12f', 'One conversation raises the base for every future raise', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('43fde1d9-cc81-4622-84d2-5de8a5f630a8', '7aaf94d5-cd5a-4f26-8bc6-3fa47f5ce12f', 'It''s guaranteed to succeed', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f790d9c9-dabc-4f20-98b8-731ac55d9b5f', '7aaf94d5-cd5a-4f26-8bc6-3fa47f5ce12f', 'It reduces your tax rate', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('0009f644-8ceb-470e-8882-b42c69c2a516', '48ef9524-bd0b-4876-b80b-eec76e7937d4', 'Side income usually triggers...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('8784b53f-1be9-4940-aecb-be647bc259cc', '0009f644-8ceb-470e-8882-b42c69c2a516', 'Self-employment tax — set aside ~25–30% of profit', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('93098e4c-53b0-462d-84f6-dbccf606580a', '0009f644-8ceb-470e-8882-b42c69c2a516', 'No tax obligations', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e61105ba-6087-41fc-b290-15dcb0d6bde0', '0009f644-8ceb-470e-8882-b42c69c2a516', 'An automatic refund', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('a48990f5-393a-4f01-a4a6-649765d28104', '62dd220a-87ed-4c8b-ae97-52a2865a8520', 'How to Negotiate', '## How to Negotiate

1. **Research market rates** for your role, level, and city — you can''t ask for a number you''ve never seen.
2. **Let them anchor first** when possible; if forced to name a number, give a range whose *bottom* you''d happily accept.
3. **Negotiate total compensation:** base, bonus, equity, PTO, remote days, start date.
4. **Practice out loud** — the words get easier.
5. **Use silence** after an offer; and always **get it in writing**.

Worst case, they say no and you''ve lost nothing. Most people never ask — which is exactly why asking works.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('94d8ab8c-9b46-4f8c-88d3-eeda8c350bb2', 'a48990f5-393a-4f01-a4a6-649765d28104', 'The most important prep before negotiating is...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b0375e56-aa20-482e-bf2d-ebecd6cd759f', '94d8ab8c-9b46-4f8c-88d3-eeda8c350bb2', 'Researching market rates for your role', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('daea3f9b-d9fe-4da6-ac92-83f1f476fbc6', '94d8ab8c-9b46-4f8c-88d3-eeda8c350bb2', 'Rehearsing an angry tone', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('6f68581d-ed07-4222-8c13-ef588e0e72d6', '94d8ab8c-9b46-4f8c-88d3-eeda8c350bb2', 'Threatening to quit', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('d1196c9f-2672-43fa-b15d-89641a511ba0', 'a48990f5-393a-4f01-a4a6-649765d28104', 'If base salary is truly fixed, you should...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('1d693a25-842f-485c-b92f-1c438d0984ce', 'd1196c9f-2672-43fa-b15d-89641a511ba0', 'Negotiate the rest — bonus, equity, PTO, remote flexibility', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('d9020f92-4e1c-43de-b385-49e5d15df918', 'd1196c9f-2672-43fa-b15d-89641a511ba0', 'Walk out immediately', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('a06e20fd-62e4-447e-b91c-811ed88709a9', 'd1196c9f-2672-43fa-b15d-89641a511ba0', 'Accept silently and stay bitter', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('faebc407-57da-4be1-a46d-430535d38fc2', 'avoiding-scams-fraud', 'Avoiding Scams & Fraud', 17, '62dd220a-87ed-4c8b-ae97-52a2865a8520');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('693ad919-9169-4c25-9787-74d7f678dea7', 'faebc407-57da-4be1-a46d-430535d38fc2', 'Red Flags', '## Red Flags

Almost every scam shares the same three ingredients:

1. **Urgency** — "act now or lose out"
2. **Secrecy** — "don''t tell anyone / this is between us"
3. **Unusual payment** — gift cards, wire transfers, crypto, payment apps

See all three? It''s a scam — no exceptions. Also automatic scams: "guaranteed returns," "risk-free," and anyone asking for your **password, full SSN, or a 2FA code**. Real banks and agencies never ask for those by phone, text, or email.

**If it sounds too good to be true, it is — and someone wants it to sound exactly that good.**', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('328c9f2d-565a-410c-968a-f895228f3dcf', '693ad919-9169-4c25-9787-74d7f678dea7', 'The classic scam payment methods are...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('08fce663-c281-4015-97e4-67265cad2ded', '328c9f2d-565a-410c-968a-f895228f3dcf', 'Gift cards, wire transfers, crypto', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('c33b7760-ea09-441e-8d2f-572bb435aad0', '328c9f2d-565a-410c-968a-f895228f3dcf', 'Credit cards and checks', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('2efc0dc0-0dcd-448f-ad05-a1d818f311cf', '328c9f2d-565a-410c-968a-f895228f3dcf', 'Bank transfers between verified accounts', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('09a59533-c58b-4693-96dc-ea6df2e538f4', '693ad919-9169-4c25-9787-74d7f678dea7', 'A caller claiming to be your bank asks for the 2FA code they just "sent you." You should...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('8e66c17f-f573-45d3-9411-ca2a8dd614a5', '09a59533-c58b-4693-96dc-ea6df2e538f4', 'Refuse and hang up — banks never ask for it', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('df11301c-5610-43b8-b023-eb8aff0d2d61', '09a59533-c58b-4693-96dc-ea6df2e538f4', 'Read it to them to be helpful', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('7ede9799-7e87-4d2f-a690-450cb81b8e12', '09a59533-c58b-4693-96dc-ea6df2e538f4', 'Text it back', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('1bce2389-bb63-4cd6-bc33-bb24d19ff74f', 'faebc407-57da-4be1-a46d-430535d38fc2', 'Protecting Yourself', '## Protecting Yourself

- **Verify independently.** Look up the official number yourself; never use the link or number in the message.
- **Slow down.** Urgency is the scammer''s main tool; legitimacy survives a night''s sleep.
- **Harden accounts:** unique passwords + 2FA everywhere; monitor statements monthly.
- **Freeze your credit** (free at all three US bureaus) if you fear identity theft — it blocks new accounts in your name without affecting your score.
- **If hit:** contact your bank immediately, report to the FTC (US) or your local equivalent, and freeze credit the same day.

Scammers hunt the rushed, the trusting, and the hopeful. Be none of the three.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('ef56c15a-6979-4e43-b264-9bf6ad8508c2', '1bce2389-bb63-4cd6-bc33-bb24d19ff74f', 'The best response to a suspicious "bank" message is to...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('827c8aeb-aa37-4257-9ac4-2c4f820cf1b7', 'ef56c15a-6979-4e43-b264-9bf6ad8508c2', 'Contact the bank through its official number or website', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('01e263c8-0e15-4fcc-8393-2b0846651d9d', 'ef56c15a-6979-4e43-b264-9bf6ad8508c2', 'Reply to the message to verify', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f66593a2-c50c-42d7-9b93-17b2d91111a0', 'ef56c15a-6979-4e43-b264-9bf6ad8508c2', 'Click the link to check', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('5cee922e-7f09-48dd-9b31-d2d4e8bf83c3', '1bce2389-bb63-4cd6-bc33-bb24d19ff74f', 'A credit freeze...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('2023805c-8bfe-43be-b81c-c615ef43f50e', '5cee922e-7f09-48dd-9b31-d2d4e8bf83c3', 'Blocks new accounts in your name — and it''s free', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('16f1aada-4124-471a-90ff-708477318b2e', '5cee922e-7f09-48dd-9b31-d2d4e8bf83c3', 'Costs a monthly fee', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('292cf13e-7c90-41e1-aaa0-5ec8af637091', '5cee922e-7f09-48dd-9b31-d2d4e8bf83c3', 'Lowers your credit score', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('ed42dcc0-e0c3-4bba-83ed-44051f69ffce', 'building-net-worth', 'Building Net Worth', 18, 'faebc407-57da-4be1-a46d-430535d38fc2');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('cc8246ae-2b98-43af-88d4-242a9ca8d635', 'ed42dcc0-e0c3-4bba-83ed-44051f69ffce', 'Assets vs. Liabilities', '## Assets vs. Liabilities

**Net worth = what you own − what you owe.**

- **Assets:** cash, savings, investments, retirement accounts, home equity — things that hold or grow value.
- **Liabilities:** credit card balances, student/auto loans, money owed to anyone.

Income is *not* wealth. A $200k earner spending $210k has negative net worth; a $60k earner investing $10k/year quietly passes them in a decade. Wealth is what''s *kept*, not what''s earned.

Every financial decision in this course ultimately does one of two things: **builds an asset or shrinks a liability.** That''s the whole game.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('ab2646c2-3a2c-4203-b883-bbbd6524791d', 'cc8246ae-2b98-43af-88d4-242a9ca8d635', 'Net worth equals...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('cdc8adec-ce62-490b-a7cb-b42288329faa', 'ab2646c2-3a2c-4203-b883-bbbd6524791d', 'Assets minus liabilities', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('d9ec24db-c666-4064-8537-660d7621b883', 'ab2646c2-3a2c-4203-b883-bbbd6524791d', 'Income minus expenses', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f8fd365a-1ea4-46dc-9aa6-13c284c31183', 'ab2646c2-3a2c-4203-b883-bbbd6524791d', 'Salary × years worked', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('1d31bbb0-5d58-42e9-b2a0-da6501b60d75', 'cc8246ae-2b98-43af-88d4-242a9ca8d635', 'A high salary guarantees...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('ede361f5-4853-4141-901e-2baf30bb9897', '1d31bbb0-5d58-42e9-b2a0-da6501b60d75', 'Nothing about net worth without spending habits', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('40c9aa1d-93f6-4da3-956a-cba3d03cfbc7', '1d31bbb0-5d58-42e9-b2a0-da6501b60d75', 'A high net worth', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('601ae8dd-b9ac-4fc4-a06f-2c05823dba4f', '1d31bbb0-5d58-42e9-b2a0-da6501b60d75', 'Financial independence', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('bcaf8eba-3393-4bb4-a1d6-0be6f6f532f1', 'ed42dcc0-e0c3-4bba-83ed-44051f69ffce', 'Tracking Progress', '## Tracking Progress

Compute net worth **once or twice a year**:

1. List every asset and its value
2. List every debt and its balance
3. Subtract. That number is your net worth.

The **trend matters more than the number** — a graph climbing from −$8k to +$5k over two years is a bigger win than a flat $50k.

Then automate the trend: payday transfers to savings (Unit 2), auto-investing (Unit 12), auto-payments on debts (Unit 7). Progress you don''t have to remember is progress that actually happens — willpower schedules, automation keeps.', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('f497278d-45dc-4671-a1cf-e2bacfc17111', 'bcaf8eba-3393-4bb4-a1d6-0be6f6f532f1', 'How often should you check your net worth?', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3575af6e-9949-4331-9279-3b5f24f8fb7d', 'f497278d-45dc-4671-a1cf-e2bacfc17111', 'Once or twice a year — the trend matters', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('0a83d488-41e0-4861-b376-cdf83eac2cfe', 'f497278d-45dc-4671-a1cf-e2bacfc17111', 'Every single day', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3e307be0-51bb-485c-a5f5-9fb59b901b2d', 'f497278d-45dc-4671-a1cf-e2bacfc17111', 'Never — it''s bad luck', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('727e677e-4cb1-41fe-a39d-5daa0923c0f2', 'bcaf8eba-3393-4bb4-a1d6-0be6f6f532f1', 'The best lens for any money decision is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('8ab070aa-ca25-40e5-8838-8e9e0adcaf59', '727e677e-4cb1-41fe-a39d-5daa0923c0f2', 'Does this build an asset or shrink a liability?', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('eedef796-d3cf-4024-a870-f928c0731ad0', '727e677e-4cb1-41fe-a39d-5daa0923c0f2', 'Will this impress people?', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('640bf6a8-61df-4cc7-9974-e9d36fd6239f', '727e677e-4cb1-41fe-a39d-5daa0923c0f2', 'Is it on sale?', 0, 2);
INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES ('6f5dc5e4-0b83-4df0-a6f5-d691d5260593', 'putting-it-together', 'Putting It Together', 19, 'ed42dcc0-e0c3-4bba-83ed-44051f69ffce');
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('bad1e356-86e9-4067-be5a-c0fc796d92db', '6f5dc5e4-0b83-4df0-a6f5-d691d5260593', 'Your Simple Plan', '## Your Simple Plan

The entire course, in order:

1. **Budget** — 50/30/20, savings moved on payday
2. **Starter emergency fund** — $500–$1,000
3. **Employer match** — capture it fully (free 50–100%)
4. **Kill high-interest debt** — 24% APR beats 7% returns
5. **Full emergency fund** — 3–6 months of essentials
6. **Invest automatically** — low-cost index funds, every month
7. **Protect** — insurance for catastrophes, 2FA everywhere
8. **Repeat for decades** — compounding does the rest

The order matters: a 24% debt is a guaranteed 24% "return" when paid off; no investment reliably beats that. And **automation beats willpower** — set the flows once, then live your life.', 0);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('d630ff54-fada-4cf7-81ee-187b7cbea71a', 'bad1e356-86e9-4067-be5a-c0fc796d92db', 'Before investing in index funds, you should typically...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('bf0ccb15-ab95-41a2-b984-f00874dc07b5', 'd630ff54-fada-4cf7-81ee-187b7cbea71a', 'Kill high-interest debt and build the emergency fund', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('b0ccca1a-52bb-482e-b373-37f9daba52dc', 'd630ff54-fada-4cf7-81ee-187b7cbea71a', 'Max out a credit card', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('7471ab72-3ba8-4031-bf9c-92ef5409d8fe', 'd630ff54-fada-4cf7-81ee-187b7cbea71a', 'Buy a house first', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('ed293d5a-3003-4c70-863b-b5e3b5c3b3e0', 'bad1e356-86e9-4067-be5a-c0fc796d92db', 'Why automate the plan?', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('537b882e-7e06-4f5b-a02e-2ecbfe117fd5', 'ed293d5a-3003-4c70-863b-b5e3b5c3b3e0', 'Willpower fails; automation makes good choices the default', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('134bd523-9063-4b55-aae3-6199111edb54', 'ed293d5a-3003-4c70-863b-b5e3b5c3b3e0', 'Automation earns extra interest', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('7e2712ac-320b-4c4b-bdf9-37d1c3677085', 'ed293d5a-3003-4c70-863b-b5e3b5c3b3e0', 'It''s legally required', 0, 2);
INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES ('64355402-7310-4fe9-9ab3-243f456d2947', '6f5dc5e4-0b83-4df0-a6f5-d691d5260593', 'The Long Game', '## The Long Game

**Financial independence** is the point where your investments can cover your living costs — work becomes a choice. Every dollar invested shortens that timeline; every dollar of lifestyle inflation extends it.

What actually gets people there is not brilliance. It''s **boring consistency**: an automatic monthly transfer into index funds, sustained for decades, through crashes and headlines.

Revisit the plan once a year — income changes, goals change, the *order* never does.

You now hold the fundamentals most people never learn: spend less than you earn, protect yourself, invest the difference, and let time do the heavy lifting. **This is educational content, not financial advice — but it''s a very good place to start.**', 1);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('bc3a7a44-1c6f-4b4c-ac99-ea756f1dddb1', '64355402-7310-4fe9-9ab3-243f456d2947', '"Financial independence" means...', 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('f86c96a4-e3d9-45ba-ab9f-26b438f62039', 'bc3a7a44-1c6f-4b4c-ac99-ea756f1dddb1', 'Your investments can cover your living expenses', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('e45cfcd1-bae9-4f43-ac13-649e2d72c2ac', 'bc3a7a44-1c6f-4b4c-ac99-ea756f1dddb1', 'You never work again under any circumstances', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('799fa7f6-f45a-4b5e-96c9-1aa5accc3eb4', 'bc3a7a44-1c6f-4b4c-ac99-ea756f1dddb1', 'You earn a six-figure salary', 0, 2);
INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES ('9f76b263-a92e-4cf4-a534-d36675a11191', '64355402-7310-4fe9-9ab3-243f456d2947', 'The strongest predictor of long-term financial success is...', 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('7540b203-c53a-41e4-97e9-8f8ba69b3480', '9f76b263-a92e-4cf4-a534-d36675a11191', 'Consistent automatic habits over decades', 1, 0);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('502f7331-d7f2-425b-8ae4-3413169685f1', '9f76b263-a92e-4cf4-a534-d36675a11191', 'Picking winning stocks', 0, 1);
INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES ('3d44878e-e564-477f-ae50-1b8d45b61fb1', '9f76b263-a92e-4cf4-a534-d36675a11191', 'Luck', 0, 2);
