-- 0005: add per-question explanations, shown after answering to teach the WHY.
-- UPDATEs are keyed by prompt (verified unique across all 80 seeded questions).

ALTER TABLE questions ADD COLUMN explanation TEXT;

UPDATE questions SET explanation = 'This course builds the core concepts and habits — budgeting, saving, investing — that most people never formally learn.' WHERE prompt = 'What is the main goal of this course?';
UPDATE questions SET explanation = 'Habits like budgeting and saving work at any income — and small amounts compound dramatically over time.' WHERE prompt = 'True or false: understanding money matters even if you don''t earn a lot.';
UPDATE questions SET explanation = 'It names an exact amount, a purpose, and a deadline — the three traits that make a goal actionable.' WHERE prompt = 'Which of these is the BEST example of a specific financial goal?';
UPDATE questions SET explanation = 'A deadline creates urgency and lets you check progress — "someday" goals rarely get started.' WHERE prompt = 'A good financial goal should be specific, measurable, and...';
UPDATE questions SET explanation = 'Spending more than you earn is a deficit — it must be covered by debt or savings, and it compounds against you.' WHERE prompt = 'You earn $3,000 a month and spend $3,200. You have a...';
UPDATE questions SET explanation = 'A budget is a plan made before the month starts, so money goes where you decide — not wherever it drifts.' WHERE prompt = 'What is a budget, most simply?';
UPDATE questions SET explanation = 'The 20% is what builds your future: savings, investing, and paying down debt faster than minimums.' WHERE prompt = 'In the 50/30/20 rule, what does the 20% represent?';
UPDATE questions SET explanation = 'Pay-yourself-first works because money you never see never gets spent — leftover money reliably disappears.' WHERE prompt = 'Why save money on payday instead of at the end of the month?';
UPDATE questions SET explanation = 'Groceries sustain you — the other options are preferences, not survival.' WHERE prompt = 'Which of these is clearly a NEED?';
UPDATE questions SET explanation = 'The same expense can be a need for one person and a want for another — the test is whether YOUR circumstances require it.' WHERE prompt = 'The needs-vs-wants test is best described as...';
UPDATE questions SET explanation = 'Small recurring charges feel trivial monthly but cost 12× per year — $12 × 12 = $144.' WHERE prompt = 'A $12/month subscription costs how much per year?';
UPDATE questions SET explanation = 'Reframing to the annual cost breaks the "it''s only $12" illusion that keeps dead subscriptions alive.' WHERE prompt = 'What''s the best question to ask about a recurring charge?';
UPDATE questions SET explanation = 'The fund''s whole job is to absorb shocks — job loss, repairs, medical bills — without forcing you into debt.' WHERE prompt = 'The main purpose of an emergency fund is to...';
UPDATE questions SET explanation = 'A surprise repair is exactly the kind of genuine emergency the fund exists for; planned expenses aren''t.' WHERE prompt = 'Which of these is a proper emergency-fund use?';
UPDATE questions SET explanation = 'Three to six months of essentials buys time to find work or absorb a shock without panic.' WHERE prompt = 'A full emergency fund typically covers how many months of ESSENTIAL expenses?';
UPDATE questions SET explanation = 'Separate and high-yield means it grows a little, stays instantly accessible, and isn''t tempting for everyday spending.' WHERE prompt = 'Where should an emergency fund live?';
UPDATE questions SET explanation = 'Good debt buys something that grows in value or income — a degree with strong job prospects can pay for itself many times over.' WHERE prompt = 'Which is the BEST example of potentially good debt?';
UPDATE questions SET explanation = 'The purpose determines whether the debt builds your future (education, assets) or drains it (consumption).' WHERE prompt = 'The key question for judging debt is...';
UPDATE questions SET explanation = '24% of $1,000 is $240 per year — high APRs make balances grow shockingly fast, which is why they''re priority one to kill.' WHERE prompt = 'Roughly how much interest per year does a $1,000 balance at 24% APR cost?';
UPDATE questions SET explanation = 'Triple-digit effective APRs make balances double or worse within months — they turn a shortfall into a debt spiral.' WHERE prompt = 'Why are payday loans considered dangerous?';
UPDATE questions SET explanation = 'On-time payments are roughly 35% of a typical score — nothing else comes close, and one missed payment does real damage.' WHERE prompt = 'Which factor has the BIGGEST impact on a typical credit score?';
UPDATE questions SET explanation = 'Keeping utilization under ~30% (lower is better) shows lenders you use credit without leaning on it.' WHERE prompt = 'As a rule of thumb, keep credit card utilization below...';
UPDATE questions SET explanation = 'A better score means a lower rate; over 30 years on a large mortgage, fractions of a percent add up to five figures.' WHERE prompt = 'On a large mortgage, a better credit score can save you...';
UPDATE questions SET explanation = 'Automation makes the single biggest scoring factor — on-time payments — happen by default, for free.' WHERE prompt = 'What''s the cheapest way to protect your credit score?';
UPDATE questions SET explanation = 'Avalanche targets the highest interest rate first, which mathematically minimizes total interest paid.' WHERE prompt = 'Which debt-payoff method targets the highest APR balance first?';
UPDATE questions SET explanation = 'The best method on paper loses to the one you actually finish — consistency beats optimization.' WHERE prompt = 'The most important factor in choosing a payoff method is...';
UPDATE questions SET explanation = 'After the intro period the rate often jumps above 20%, so the transferred balance must be gone before it ends.' WHERE prompt = 'A 0% balance-transfer card becomes a trap when...';
UPDATE questions SET explanation = 'Closing the card shrinks your total credit and average account age — both hurt your score; just don''t carry a balance.' WHERE prompt = 'After paying off a credit card, you should generally...';
UPDATE questions SET explanation = 'Checking is built for transactions — bill pay, debit card, frequent in-and-out — with no withdrawal limits.' WHERE prompt = 'Which account is designed for daily spending and bills?';
UPDATE questions SET explanation = 'At ~4% vs ~0.01%, the same $10,000 earns about $400/year instead of $1 — same FDIC safety, very different outcome.' WHERE prompt = 'Why keep savings in an HYSA instead of a big-bank savings account?';
UPDATE questions SET explanation = 'Maintenance fees are pure waste — thousands of banks and credit unions waive them or don''t charge at all.' WHERE prompt = 'The most reliably avoidable bank fee is...';
UPDATE questions SET explanation = 'A declined card is embarrassing for a second; an overdraft fee plus a negative balance is a hole that can snowball.' WHERE prompt = 'If you opt out of overdraft "protection," a purchase you can''t afford will...';
UPDATE questions SET explanation = 'The Rule of 72: divide 72 by the return rate — 72 ÷ 8 = 9 years per doubling.' WHERE prompt = 'Using the Rule of 72, money invested at 8% doubles roughly every...';
UPDATE questions SET explanation = 'The same compounding that grows investments grows debt balances — at 24% APR, fast.' WHERE prompt = 'Compound interest works AGAINST you when you...';
UPDATE questions SET explanation = 'The extra decade means one more doubling cycle — the early saver ends with more than double.' WHERE prompt = 'Two people save $200/month at 7% until 65 — one from age 25, one from 35. Who ends with more?';
UPDATE questions SET explanation = 'Rate matters, but time dominates — years invested is the exponent in the compound growth formula.' WHERE prompt = 'The most powerful input to compound growth is...';
UPDATE questions SET explanation = 'Real return strips out rising prices to show what your money actually gained in purchasing power.' WHERE prompt = 'Real return is calculated as...';
UPDATE questions SET explanation = '1% − 3% = −2%: your dollar number grows but buys less each year — cash loses ground to inflation.' WHERE prompt = 'Your savings pay 1% while inflation runs 3%. Your real return is...';
UPDATE questions SET explanation = 'Over long periods, equities have historically outpaced inflation; cash and bonds often haven''t.' WHERE prompt = 'Over the long run, which has most reliably beaten inflation?';
UPDATE questions SET explanation = 'The fund trades growth for certainty — investing it risks it being down exactly when you need it most.' WHERE prompt = 'Why doesn''t the emergency fund need to beat inflation?';
UPDATE questions SET explanation = 'A share is literal ownership — you profit if the company grows and share in its value.' WHERE prompt = 'Owning one share of stock means you...';
UPDATE questions SET explanation = 'One basket holding hundreds of companies can''t be wiped out by a single failure — that''s diversification.' WHERE prompt = 'Compared to a single stock, a fund is...';
UPDATE questions SET explanation = 'Stocks can drop 30% in a bad year; money you need next year can''t wait out a downturn.' WHERE prompt = 'Money you need for a down payment next year should be...';
UPDATE questions SET explanation = 'Return is compensation for risk — anything promising high returns safely is lying or hiding the risk.' WHERE prompt = '"Higher expected return" in investing always comes with...';
UPDATE questions SET explanation = 'An index fund simply mirrors the index — no picking, just owning the market as-is.' WHERE prompt = 'An S&P 500 index fund holds...';
UPDATE questions SET explanation = 'Fees come out every year regardless of performance, so 1% extra compounds into a huge drag over decades.' WHERE prompt = 'Why do fund fees matter so much?';
UPDATE questions SET explanation = 'The market''s best days cluster near its worst — being out at the right time requires being right twice, constantly.' WHERE prompt = '"Time in the market beats timing the market" means...';
UPDATE questions SET explanation = 'Enron and Lehman went to zero while the market recovered — diversification is the shield.' WHERE prompt = 'The key danger of holding a single company''s stock is...';
UPDATE questions SET explanation = 'Outside these accounts, yearly taxes eat returns; inside, every dollar of gain stays invested and compounds.' WHERE prompt = 'The key benefit of investing inside a retirement account is...';
UPDATE questions SET explanation = 'Roth trades a small tax bill today for decades of untaxed growth and tax-free withdrawals.' WHERE prompt = 'With a Roth-style account, taxes are paid...';
UPDATE questions SET explanation = 'Every matched dollar is free money added on top — a guaranteed 50% gain before any investing.' WHERE prompt = 'A 50% match on contributions is effectively...';
UPDATE questions SET explanation = 'Markets average ~7–10%; a match pays 50% instantly with zero risk — the best deal in personal finance.' WHERE prompt = 'Why capture the full match before other investing?';
UPDATE questions SET explanation = 'Brackets are marginal — each slice of income is taxed at its own rate, so a raise never reduces your take-home.' WHERE prompt = 'You move into a higher tax bracket. What happens?';
UPDATE questions SET explanation = 'Effective rate blends all your brackets; it''s the honest number for what you actually pay.' WHERE prompt = 'Your effective tax rate is...';
UPDATE questions SET explanation = 'A credit cuts the bill itself ($1,000 credit = $1,000 less); a deduction only removes taxable income.' WHERE prompt = 'Which reduces your tax bill dollar-for-dollar?';
UPDATE questions SET explanation = 'A refund is your own money returned without interest — better to have it each month, invested or against debt.' WHERE prompt = 'A big tax refund every year usually means...';
UPDATE questions SET explanation = 'You pay a known small cost to cap an unknown catastrophic one — that''s the entire trade.' WHERE prompt = 'The core purpose of insurance is to...';
UPDATE questions SET explanation = 'The deductible is your share before coverage kicks in; higher deductibles mean lower premiums.' WHERE prompt = 'A deductible is...';
UPDATE questions SET explanation = 'Term life replaces your income for people who depend on it — no dependents, no need.' WHERE prompt = 'Who most needs term life insurance?';
UPDATE questions SET explanation = 'Gadget warranties cost more than expected repairs and duplicate coverage you may already have — pure margin for the seller.' WHERE prompt = 'Which is usually NOT worth the price?';
UPDATE questions SET explanation = 'Depreciation is steepest in year one — buying 2–3 years used lets someone else absorb it.' WHERE prompt = 'A new car typically loses about what share of its value in the first year?';
UPDATE questions SET explanation = 'The rule keeps the down payment real, the loan short, and the total cost within ~10% of take-home so it can''t crowd out savings.' WHERE prompt = 'The 20/4/10 guideline suggests...';
UPDATE questions SET explanation = 'Transaction costs of buying and selling take years to recoup; staying 5+ years is when buying tends to win.' WHERE prompt = 'Renting is often the right call when...';
UPDATE questions SET explanation = 'A $400k home needs roughly $4–8k/year of maintenance alone — on top of taxes and insurance.' WHERE prompt = 'Beyond the mortgage, yearly maintenance alone typically costs about what % of a home''s value?';
UPDATE questions SET explanation = 'Raises, bonuses, and future offers all key off your current salary — one conversation compounds for a career.' WHERE prompt = 'Why is salary negotiation such a high-ROI move?';
UPDATE questions SET explanation = 'Side income gets no withholding, and self-employment tax adds ~15% on top of income tax — set it aside or get surprised.' WHERE prompt = 'Side income usually triggers...';
UPDATE questions SET explanation = 'You can''t ask credibly without knowing the range — data is your leverage, not adjectives.' WHERE prompt = 'The most important prep before negotiating is...';
UPDATE questions SET explanation = 'Total comp has many levers — bonus, equity, PTO, remote — base is just one of them.' WHERE prompt = 'If base salary is truly fixed, you should...';
UPDATE questions SET explanation = 'These methods are irreversible and untraceable — exactly why scammers demand them.' WHERE prompt = 'The classic scam payment methods are...';
UPDATE questions SET explanation = 'A 2FA code is the last lock on your account; real banks never need it — only attackers do.' WHERE prompt = 'A caller claiming to be your bank asks for the 2FA code they just "sent you." You should...';
UPDATE questions SET explanation = 'Verification must happen through a channel YOU chose — the contact info in the message is the trap.' WHERE prompt = 'The best response to a suspicious "bank" message is to...';
UPDATE questions SET explanation = 'A freeze stops anyone — including impostors — from opening credit in your name; it''s free by law and doesn''t hurt your score.' WHERE prompt = 'A credit freeze...';
UPDATE questions SET explanation = 'Net worth is the honest scoreboard: what you own after every debt is settled.' WHERE prompt = 'Net worth equals...';
UPDATE questions SET explanation = 'Income isn''t wealth — a $200k earner spending $210k goes backwards while a modest saver compounds.' WHERE prompt = 'A high salary guarantees...';
UPDATE questions SET explanation = 'The direction over years is the signal; checking daily just adds noise and anxiety.' WHERE prompt = 'How often should you check your net worth?';
UPDATE questions SET explanation = 'Every money move lands on one side of that ledger — the simplest test of whether a decision builds wealth.' WHERE prompt = 'The best lens for any money decision is...';
UPDATE questions SET explanation = 'Paying off 24% APR debt is a guaranteed 24% return — no investment reliably beats that, so order matters.' WHERE prompt = 'Before investing in index funds, you should typically...';
UPDATE questions SET explanation = 'Automation removes the monthly decision — good choices happen even on your worst days.' WHERE prompt = 'Why automate the plan?';
UPDATE questions SET explanation = 'FI is when work becomes optional: your portfolio, not your paycheck, pays your life.' WHERE prompt = '"Financial independence" means...';
UPDATE questions SET explanation = 'Boring consistency beats brilliance — the investors who win are the ones who never stop.' WHERE prompt = 'The strongest predictor of long-term financial success is...';
