// Compiles worker/seed/units.json into numbered SQL migrations under worker/migrations/.
// Run with: node worker/seed/generate-seed-sql.ts
//
// Incremental by design: earlier seed migrations may already be applied to local and
// remote D1 databases, and D1 never re-runs an applied migration. So this script:
//   - skips any unit whose slug already appears in a prior migration (append-only
//     content pipeline — editing an already-seeded unit needs a hand-written migration);
//   - emits only NEW units into the next numbered migration file (0003, 0004, ...);
//   - resolves unlock_requires_unit_slug against both prior-migration IDs and new IDs.
// If there is nothing new, no file is written.
import { randomUUID } from 'node:crypto'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

type Option = { label: string; isCorrect: boolean }
type Question = { prompt: string; options: Option[] }
type Lesson = { title: string; conceptMarkdown: string; questions: Question[] }
type Unit = { slug: string; title: string; unlockRequiresUnitSlug: string | null; lessons: Lesson[] }
type SeedFile = { units: Unit[] }

const __dirname = dirname(fileURLToPath(import.meta.url))
const unitsJsonPath = join(__dirname, 'units.json')
const migrationsDir = join(__dirname, '..', 'migrations')

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function main() {
  const seed = JSON.parse(readFileSync(unitsJsonPath, 'utf-8')) as SeedFile

  // All prior migration SQL, in order.
  const priorFiles = readdirSync(migrationsDir)
    .filter((f) => /^\d{4}_.*\.sql$/.test(f))
    .sort()
  const priorSql = priorFiles.map((f) => readFileSync(join(migrationsDir, f), 'utf-8')).join('\n')

  // Unit IDs already seeded, parsed from prior migrations (slugs are [a-z0-9-], so
  // no SQL-escaping edge cases in the captured groups).
  const existingUnitIdBySlug = new Map<string, string>()
  for (const m of priorSql.matchAll(
    /INSERT INTO units \(id, slug, title, sort_order, unlock_requires_unit_id\) VALUES \('([0-9a-f-]{36})', '([a-z0-9-]+)'/g,
  )) {
    existingUnitIdBySlug.set(m[2], m[1])
  }

  const seenSlugs = new Set<string>()
  for (const unit of seed.units) {
    if (seenSlugs.has(unit.slug)) throw new Error(`Duplicate unit slug in units.json: ${unit.slug}`)
    seenSlugs.add(unit.slug)
  }

  // A unit is "new" if its quoted slug never appears in a prior migration.
  const newUnits = seed.units.filter((u) => !priorSql.includes(`'${u.slug}'`))
  if (newUnits.length === 0) {
    console.log('No new units in units.json — nothing to generate.')
    return
  }

  // Pre-assign IDs for all new units so unlock references resolve regardless of order.
  const newUnitIdBySlug = new Map(newUnits.map((u) => [u.slug, randomUUID()]))
  const unitIdBySlug = (slug: string): string => {
    const id = newUnitIdBySlug.get(slug) ?? existingUnitIdBySlug.get(slug)
    if (!id) throw new Error(`unlockRequiresUnitSlug references unknown unit slug: ${slug}`)
    return id
  }

  const lines: string[] = ['-- Generated by worker/seed/generate-seed-sql.ts from worker/seed/units.json. Do not hand-edit.']

  for (const unit of newUnits) {
    const unitId = newUnitIdBySlug.get(unit.slug)!
    const unlockId = unit.unlockRequiresUnitSlug ? unitIdBySlug(unit.unlockRequiresUnitSlug) : null
    const sortOrder = seed.units.findIndex((u) => u.slug === unit.slug)
    lines.push(
      `INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES (${sqlString(unitId)}, ${sqlString(unit.slug)}, ${sqlString(unit.title)}, ${sortOrder}, ${unlockId ? sqlString(unlockId) : 'NULL'});`,
    )

    unit.lessons.forEach((lesson, lessonIndex) => {
      const lessonId = randomUUID()
      lines.push(
        `INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES (${sqlString(lessonId)}, ${sqlString(unitId)}, ${sqlString(lesson.title)}, ${sqlString(lesson.conceptMarkdown)}, ${lessonIndex});`,
      )

      lesson.questions.forEach((question, questionIndex) => {
        const questionId = randomUUID()
        lines.push(
          `INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES (${sqlString(questionId)}, ${sqlString(lessonId)}, ${sqlString(question.prompt)}, ${questionIndex});`,
        )

        question.options.forEach((option, optionIndex) => {
          const optionId = randomUUID()
          lines.push(
            `INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES (${sqlString(optionId)}, ${sqlString(questionId)}, ${sqlString(option.label)}, ${option.isCorrect ? 1 : 0}, ${optionIndex});`,
          )
        })
      })
    })
  }

  const nextNumber = priorFiles.length > 0 ? Math.max(...priorFiles.map((f) => Number(f.slice(0, 4)))) + 1 : 1
  const outputPath = join(migrationsDir, `${String(nextNumber).padStart(4, '0')}_seed_content.sql`)
  if (existsSync(outputPath)) throw new Error(`Refusing to overwrite existing migration: ${outputPath}`)
  writeFileSync(outputPath, lines.join('\n') + '\n', 'utf-8')
  console.log(`Seeded ${newUnits.length} new unit(s) [${newUnits.map((u) => u.slug).join(', ')}] -> ${outputPath}`)
}

main()
