// Compiles worker/seed/units.json into a SQL migration (worker/migrations/0002_seed_content.sql).
// Run with: node worker/seed/generate-seed-sql.ts
// Re-run after editing units.json; review the diff before committing, since this regenerates IDs.
import { randomUUID } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

type Option = { label: string; isCorrect: boolean }
type Question = { prompt: string; options: Option[] }
type Lesson = { title: string; conceptMarkdown: string; questions: Question[] }
type Unit = { slug: string; title: string; unlockRequiresUnitSlug: string | null; lessons: Lesson[] }
type SeedFile = { units: Unit[] }

const __dirname = dirname(fileURLToPath(import.meta.url))
const unitsJsonPath = join(__dirname, 'units.json')
const outputPath = join(__dirname, '..', 'migrations', '0002_seed_content.sql')

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function main() {
  const seed = JSON.parse(readFileSync(unitsJsonPath, 'utf-8')) as SeedFile
  const lines: string[] = ['-- Generated by worker/seed/generate-seed-sql.ts from worker/seed/units.json. Do not hand-edit.']

  const unitIdBySlug = new Map<string, string>()
  for (const unit of seed.units) {
    unitIdBySlug.set(unit.slug, randomUUID())
  }

  seed.units.forEach((unit, unitIndex) => {
    const unitId = unitIdBySlug.get(unit.slug)!
    const unlockId = unit.unlockRequiresUnitSlug ? unitIdBySlug.get(unit.unlockRequiresUnitSlug) : null
    lines.push(
      `INSERT INTO units (id, slug, title, sort_order, unlock_requires_unit_id) VALUES (${sqlString(unitId)}, ${sqlString(unit.slug)}, ${sqlString(unit.title)}, ${unitIndex}, ${unlockId ? sqlString(unlockId) : 'NULL'});`,
    )

    unit.lessons.forEach((lesson, lessonIndex) => {
      const lessonId = randomUUID()
      lines.push(
        `INSERT INTO lessons (id, unit_id, title, concept_markdown, sort_order) VALUES (${sqlString(lessonId)}, ${sqlString(unitId)}, ${sqlString(lesson.title)}, ${sqlString(lesson.conceptMarkdown)}, ${lessonIndex});`,
      )

      lesson.questions.forEach((question, questionIndex) => {
        const questionId = randomUUID()
        lines.push(
          `INSERT INTO questions (id, lesson_id, prompt, sort_order) VALUES (${sqlString(questionId)}, ${sqlString(lessonId)}, ${sqlString(question.prompt)}, ${questionIndex});`,
        )

        question.options.forEach((option, optionIndex) => {
          const optionId = randomUUID()
          lines.push(
            `INSERT INTO answer_options (id, question_id, label, is_correct, sort_order) VALUES (${sqlString(optionId)}, ${sqlString(questionId)}, ${sqlString(option.label)}, ${option.isCorrect ? 1 : 0}, ${optionIndex});`,
          )
        })
      })
    })
  })

  writeFileSync(outputPath, lines.join('\n') + '\n', 'utf-8')
  console.log(`Wrote ${lines.length - 1} statements to ${outputPath}`)
}

main()
